var OMIE_APP_KEY = 'PUT_YOUR_APP_KEY_HERE';
var OMIE_APP_SECRET = 'PUT_YOUR_APP_SECRET_HERE';

var XMLHttpRequest = require("xmlhttprequest").XMLHttpRequest;
var OrdemProducaoJsonClient=function(){
	this._EndPoint="https://app.omie.com.br/api/v1/produtos/op/";
	this._Call=function(method,param,cb){
		var server= new XMLHttpRequest();
		server.open("POST",this._EndPoint,cb!=null);
		server.setRequestHeader("Content-Type","application/json");
		var req=JSON.stringify({call:method,app_key:OMIE_APP_KEY,app_secret:OMIE_APP_SECRET,param:(param)?param:[]});
		if(cb){
			server.onreadystatechange=this._EndCall;
			server.cb=cb;
			server.send(req);
			return server;
		}else{
			server.send(req);
			var res=JSON.parse(server.responseText);
			delete(server);
			return res;
		}
	};
	this._EndCall=function(e){
		var server=this;
		if(server.readyState!=4)
			return;
		if(server.status!=200)
			throw(new Exception("AJAX error "+server.status+": "+server.statusText));
		server.cb(JSON.parse(server.responseText));
		server.cb=null;
		delete(server);
	};
	this.IncluirOrdemProducao=function(
		copIncluirRequest,
		_cb
	){
		return this._Call(
			"IncluirOrdemProducao",
			[
			copIncluirRequest
			],
			(_cb)?_cb:null
		);
	};
	this.AlterarOrdemProducao=function(
		copAlterarRequest,
		_cb
	){
		return this._Call(
			"AlterarOrdemProducao",
			[
			copAlterarRequest
			],
			(_cb)?_cb:null
		);
	};
	this.UpsertOrdemProducao=function(
		copUpsertRequest,
		_cb
	){
		return this._Call(
			"UpsertOrdemProducao",
			[
			copUpsertRequest
			],
			(_cb)?_cb:null
		);
	};
	this.ExcluirOrdemProducao=function(
		copExcluirRequest,
		_cb
	){
		return this._Call(
			"ExcluirOrdemProducao",
			[
			copExcluirRequest
			],
			(_cb)?_cb:null
		);
	};
	this.ConsultarOrdemProducao=function(
		copConsultarRequest,
		_cb
	){
		return this._Call(
			"ConsultarOrdemProducao",
			[
			copConsultarRequest
			],
			(_cb)?_cb:null
		);
	};
	this.ListarOrdemProducao=function(
		copListarRequest,
		_cb
	){
		return this._Call(
			"ListarOrdemProducao",
			[
			copListarRequest
			],
			(_cb)?_cb:null
		);
	};
	this.ConcluirOrdemProducao=function(
		copConcluirRequest,
		_cb
	){
		return this._Call(
			"ConcluirOrdemProducao",
			[
			copConcluirRequest
			],
			(_cb)?_cb:null
		);
	};
	this.ReverterOrdemProducao=function(
		copReverterRequest,
		_cb
	){
		return this._Call(
			"ReverterOrdemProducao",
			[
			copReverterRequest
			],
			(_cb)?_cb:null
		);
	};
	this.cadastros=function(){
		this.identificacao=null;
		this.infAdicionais=null;
		this.observacoes=null;
		this.outrasInf=null;
		this.itens=null;
		this.itensDetalhes=null;
	};
	this.identificacao=function(){
		this.nCodOP=null;
		this.cCodIntOP=null;
		this.cNumOP=null;
		this.nCodProduto=null;
		this.cCodIntProd=null;
		this.dDtPrevisao=null;
		this.nQtde=null;
		this.codigo_local_estoque=null;
		this.lote_validade_op=null;
	};
	this.infAdicionais=function(){
		this.dDtInicio=null;
		this.dDtConclusao=null;
		this.nCodProjeto=null;
		this.cEtapa=null;
	};
	this.observacoes=function(){
		this.cObs=null;
	};
	this.outrasInf=function(){
		this.cConcluida=null;
		this.dConclusao=null;
		this.hConclusao=null;
		this.dInclusao=null;
		this.hInclusao=null;
		this.uInc=null;
		this.dAlteracao=null;
		this.hAlteracao=null;
		this.uAlt=null;
	};
	this.itens=function(){
		this.nIdProdutoMalha=null;
		this.cUtilizarDoEstoque=null;
		this.lote_validade=null;
	};
	this.itensDetalhes=function(){
		this.nIdProdutoMalha=null;
		this.cUtilizarDoEstoque=null;
		this.nQtde=null;
		this.codigo_local_estoque=null;
		this.cObs=null;
		this.info=null;
	};
	this.copAlterarRequest=function(){
		this.identificacao=null;
		this.infAdicionais=null;
		this.observacoes=null;
		this.outrasInf=null;
		this.itens=null;
	};
	this.copAlterarResponse=function(){
		this.nCodOP=null;
		this.cCodIntOP=null;
		this.cCodStatus=null;
		this.cDesStatus=null;
	};
	this.copConcluirRequest=function(){
		this.nCodOP=null;
		this.cCodIntOP=null;
		this.dDtConclusao=null;
		this.nQtdeProduzida=null;
		this.cObsConclusao=null;
	};
	this.copConcluirResponse=function(){
		this.nCodOP=null;
		this.cCodIntOP=null;
		this.cCodStatus=null;
		this.cDesStatus=null;
	};
	this.copConsultarRequest=function(){
		this.nCodOP=null;
		this.cCodIntOP=null;
	};
	this.copConsultarResponse=function(){
		this.identificacao=null;
		this.infAdicionais=null;
		this.observacoes=null;
		this.outrasInf=null;
		this.itens=null;
		this.itensDetalhes=null;
	};
	this.copExcluirRequest=function(){
		this.nCodOP=null;
		this.cCodIntOP=null;
	};
	this.copExcluirResponse=function(){
		this.nCodOP=null;
		this.cCodIntOP=null;
		this.cCodStatus=null;
		this.cDesStatus=null;
	};
	this.copIncluirRequest=function(){
		this.identificacao=null;
		this.infAdicionais=null;
		this.observacoes=null;
		this.outrasInf=null;
		this.itens=null;
	};
	this.copIncluirResponse=function(){
		this.nCodOP=null;
		this.cCodIntOP=null;
		this.cCodStatus=null;
		this.cDesStatus=null;
	};
	this.copListarRequest=function(){
		this.pagina=null;
		this.registros_por_pagina=null;
		this.apenas_importado_api=null;
		this.ordenar_por=null;
		this.ordem_decrescente=null;
		this.nCodProjeto=null;
		this.nIdProd=null;
		this.lExibirItens=null;
		this.dDtConclusaoDe=null;
		this.dDtConclusaoAte=null;
	};
	this.copListarResponse=function(){
		this.pagina=null;
		this.total_de_paginas=null;
		this.registros=null;
		this.total_de_registros=null;
		this.cadastros=null;
	};
	this.copReverterRequest=function(){
		this.nCodOP=null;
		this.cCodIntOP=null;
	};
	this.copReverterResponse=function(){
		this.nCodOP=null;
		this.cCodIntOP=null;
		this.cCodStatus=null;
		this.cDesStatus=null;
	};
	this.copUpsertRequest=function(){
		this.identificacao=null;
		this.infAdicionais=null;
		this.observacoes=null;
		this.outrasInf=null;
		this.itens=null;
	};
	this.copUpsertResponse=function(){
		this.nCodOP=null;
		this.cCodIntOP=null;
		this.cCodStatus=null;
		this.cDesStatus=null;
	};
	this.lote_validade_op=function(){
		this.nIdLote=null;
	};
	this.info=function(){
		this.dInc=null;
		this.hInc=null;
		this.uInc=null;
		this.dAlt=null;
		this.hAlt=null;
		this.uAlt=null;
	};
	this.lote_validade=function(){
		this.nIdLote=null;
		this.nQtdLote=null;
	};
	this.omie_fail=function(){
		this.code=null;
		this.description=null;
		this.referer=null;
		this.fatal=null;
	};
};
module.exports = OrdemProducaoJsonClient;