import { describe, expect, it, vi } from 'vitest';
import { createCalendarGateway, type ReservationPayload } from './calendarGateway';
const payload: ReservationPayload={data:'2026-08-21',tipo:'Auditório',tema:'Reunião',inicio:'08:00',fim:'09:00',repetir:false,repetirTodosMeses:false,diasSemana:[],cafe:false,avisoEmail:false,avisoWhatsapp:false,criadoPor:'jair',participantes:[],participantesAvisos:{},descricao:null,visitantes:null,linkReuniao:null,anexoUrl:null,anexoNome:null};
const response=(data:unknown,ok=true)=>Promise.resolve({ok,status:ok?200:400,json:()=>Promise.resolve(data)} as Response);
describe('calendarGateway',()=>{
 it('lê reservas e lembretes do contrato legado',async()=>{const fetcher=vi.fn().mockImplementation((url:string)=>url.includes('reservas?')?response({reservas:[{id:1}]}):response({lembretes:[{id:2}]})); const result=await createCalendarGateway(fetcher).listMonth(2026,8,'Jair Silva'); expect(result.reservations).toHaveLength(1); expect(fetcher).toHaveBeenCalledWith('/api/rh/lembretes?ano=2026&mes=8&user=Jair%20Silva',expect.objectContaining({credentials:'include'}));});
 it('bloqueia mutação sem confirmação antes do fetch',()=>{const fetcher=vi.fn(); expect(()=>createCalendarGateway(fetcher).createReservation(payload)).toThrow('Confirmação obrigatória'); expect(fetcher).not.toHaveBeenCalled();});
 it('envia payload real somente após confirmação',async()=>{const fetcher=vi.fn().mockReturnValue(response({ok:true,ids:[7]})); await createCalendarGateway(fetcher).createReservation(payload,true); expect(fetcher).toHaveBeenCalledWith('/api/rh/reservas',expect.objectContaining({method:'POST',body:JSON.stringify(payload),credentials:'include'}));});
 it('expõe leitura de ata, notas, presença e anexos',async()=>{const fetcher=vi.fn().mockImplementation((url:string)=>response(url.includes('/atas?')?{atas:[]}:url.includes('/notas?')?{notas:[]}:url.includes('/presenca')?{registros:[]}:[])); const gateway=createCalendarGateway(fetcher); await Promise.all([gateway.listMinutes(3),gateway.listNotes(3),gateway.listAttendance(3),gateway.listAttachments(3)]); expect(fetcher.mock.calls.map(c=>c[0])).toEqual(['/api/rh/atas?reserva_id=3','/api/rh/notas?reserva_id=3','/api/rh/reservas/3/presenca','/api/rh/reservas/3/anexos']);});
});
