import type { PirCodeSummary, PirInspectionInput, PirMode, PirPendingItem, PirPlanItem, PirProductOption, PirReportItem } from '../features/pir/types'

const apiBase = import.meta.env.VITE_API_BASE_URL || ''
export class PirGatewayError extends Error { readonly status?: number; readonly data?: Record<string, unknown>; constructor(message: string, status?: number, data?: Record<string, unknown>) { super(message); this.status = status; this.data = data } }
async function request<T>(path: string, init: RequestInit = {}) { const headers = new Headers(init.headers); headers.set('Accept', 'application/json'); if (init.body && !(init.body instanceof FormData)) headers.set('Content-Type', 'application/json'); let response: Response; try { response = await fetch(`${apiBase}${path}`, { ...init, headers, credentials: 'include', cache: 'no-store' }) } catch (error) { throw new PirGatewayError(error instanceof Error ? error.message : 'Falha de conexão.') } const raw = await response.text(); let data: Record<string, unknown> = {}; try { data = raw ? JSON.parse(raw) : {} } catch { data = { error: raw } } if (!response.ok || data.ok === false) throw new PirGatewayError(typeof data.error === 'string' ? data.error : `Falha HTTP ${response.status}`, response.status, data); return data as T }
const body = (value: unknown) => JSON.stringify(value)
export function loadPirPending(query = '', mode: PirMode = 'mp') { const params = new URLSearchParams(); if (query.trim()) params.set('q', query.trim()); if (mode === 'sem_mp') params.set('sem_mp', '1'); if (mode === 'eng') params.set('necessario_eng', '1'); const suffix = params.toString(); return request<{ etiquetas: PirPendingItem[]; filtro: string }>(`/api/etiquetas/recebimento/pendentes-pir${suffix ? `?${suffix}` : ''}`) }
export function searchPirProducts(query: string) { return request<{ itens: PirProductOption[] }>('/api/produtos/busca', { method: 'POST', body: body({ q: query.trim() }) }) }
export function loadPirPlan(idOmie: string | number) { return request<PirPlanItem[]>(`/api/pir/${encodeURIComponent(String(idOmie))}`) }
export function loadProductPhotos(code: string) { return request<{ ok: boolean; fotos: Array<{ id?: number; pos?: number; url_imagem: string }> }>(`/api/produtos/${encodeURIComponent(code)}/fotos`) }
export function uploadProductPhoto(code: string, file: File) { const form = new FormData(); form.append('foto', file); form.append('nome_foto', file.name || 'foto'); form.append('descricao_foto', 'PIR_ENG'); return request<{ ok: boolean; url?: string }>(`/api/produtos/${encodeURIComponent(code)}/fotos?pos=0`, { method: 'POST', body: form }) }
export function getProductCustom(code: string) { return request<{ produto_customizado: boolean }>(`/api/produtos/${encodeURIComponent(code)}/produto-customizado`) }
export function setProductCustom(code: string, value: boolean) { return request<{ ok: boolean }>(`/api/produtos/${encodeURIComponent(code)}/produto-customizado`, { method: 'PUT', body: body({ produto_customizado: value }) }) }
export function getDirectIdentification(code: string) { return request<{ pir_vai_direto_identificacao: boolean }>(`/api/produtos/${encodeURIComponent(code)}/pir-vai-direto-identificacao`) }
export function setDirectIdentification(code: string, value: boolean) { return request<{ ok: boolean }>(`/api/produtos/${encodeURIComponent(code)}/pir-vai-direto-identificacao`, { method: 'PUT', body: body({ pir_vai_direto_identificacao: value }) }) }
export function setNecessaryEngineering(id: number, code: string, value: boolean) { return request<{ ok: boolean }>(`/api/etiquetas/recebimento/${id}/necessario-eng`, { method: 'PATCH', body: body({ necessario_eng: value }) }).then(async (result) => { await request(`/api/produtos/${encodeURIComponent(code)}/pir-necessario-eng`, { method: 'PUT', body: body({ pir_necessario_eng: value }) }); return result }) }
export function registerPirInspection(input: PirInspectionInput) { return request<{ ok: boolean; id: number }>('/api/qualidade/produtos-liberado', { method: 'POST', body: body(input) }) }
export function releasePirReceipt(id: number) { return request<{ ok: boolean }>(`/api/etiquetas/recebimento/${id}/pir`, { method: 'PATCH', body: body({ pir: true }) }) }
export async function decidePirEngineering(input: { status: 'aprovado' | 'reprovado' | 'projeto'; codigo_produto: string; codigo: string; etq_recebimento_id: number }) { await request('/api/engenharia/produto-aprovacao', { method: 'POST', body: body(input) }); return request<{ ok: boolean; transferencia?: { ok?: boolean; error?: string; ids?: number[] } }>(`/api/etiquetas/recebimento/${input.etq_recebimento_id}/pir-eng-status`, { method: 'PATCH', body: body({ status: input.status }) }) }
export function loadPirReport() { return request<{ ok: boolean; itens: PirReportItem[] }>('/api/qualidade/produtos-liberado') }
export function loadPirCodes(source: 'pir' | 'produtos_omie') { return request<{ total: number; itens: PirCodeSummary[] }>(`/api/pir/resumo/${source === 'pir' ? 'codigos' : 'produtos-omie'}`) }
export function setPirVerification(code: string, value: boolean) { return request<{ codigo: string; pir: boolean }>(`/api/pir/produto/${encodeURIComponent(code)}/verificacao`, { method: 'PUT', body: body({ pir: value }) }) }
export function createPirPlanItem(input: { id_omie: string | number; codigo: string; frequencia: 10 | 50 | 100; o_que_verificar: string; foto_url?: string | null }) { return request<PirPlanItem>('/api/pir', { method: 'POST', body: body(input) }) }
