import type { ProductionActionInput,ProductionOrder,ProductionProgram,ProductionSaleOrder,ProductionSnapshot,ProductionStop } from '../features/production-registration/types'
const base=import.meta.env.VITE_API_BASE_URL||''
export class ProductionRegistrationError extends Error{readonly status?:number;constructor(message:string,status?:number){super(message);this.status=status}}
async function request<T>(path:string,init:RequestInit={}){const headers=new Headers(init.headers);headers.set('Accept','application/json');if(init.body)headers.set('Content-Type','application/json');let response:Response;try{response=await fetch(`${base}${path}`,{...init,headers,credentials:'include',cache:'no-store'})}catch(e){throw new ProductionRegistrationError(e instanceof Error?e.message:'Falha de conexão.')}const raw=await response.text();let data:Record<string,unknown>={};try{data=raw?JSON.parse(raw):{}}catch{data={error:raw}}if(!response.ok||data.success===false||data.ok===false)throw new ProductionRegistrationError(typeof data.error==='string'?data.error:`Falha HTTP ${response.status}`,response.status);return data as T}
const post=<T>(path:string,body:unknown)=>request<T>(path,{method:'POST',body:JSON.stringify(body)})
export async function loadProductionSnapshot():Promise<ProductionSnapshot>{const [o,s,p]=await Promise.all([request<{success:boolean;ordens:ProductionOrder[]}>('/api/producao/ordens'),request<{success:boolean;pedidos:ProductionSaleOrder[]}>('/api/producao/pedidos-kanban'),request<{success:boolean;registros:ProductionProgram[]}>('/api/producao/kanban-programacao')]);const ops=(o.ordens||[]).map(x=>{const reg=(p.registros||[]).find(r=>r.op_producao_id===x.id||String(r.numero_op||'').toUpperCase()===String(x.identificacao||x.n_op||'').toUpperCase());return{op_producao_id:x.id,numero_op:x.identificacao||x.n_op||'',kanban_programacao_id:reg?.id||null}});const [ri,stops,times,occ]=ops.length?await Promise.all([post<{ok:boolean;status_por_op?:Record<string,unknown>;ri_por_op?:Record<string,unknown>}>('/api/qualidade/ri-check/status-por-ops',{ops}),post<{success:boolean;paradas_por_op:Record<string,ProductionStop>}>('/api/producao/paradas/ativas-por-ops',{ops}),post<{success:boolean;tempos_por_op:Record<string,unknown>}>('/api/producao/tempo/ativos-por-ops',{ops}),post<{ok:boolean;por_op:Record<string,unknown>}>('/api/qualidade/ri-check/ocorrencias-por-ops',{ops})]):[{},{},{},{}] as const;return{orders:o.ordens||[],sales:s.pedidos||[],programs:p.registros||[],riByOrder:{...('ri_por_op'in ri?ri.ri_por_op||{}:{}),...('status_por_op'in ri?ri.status_por_op||{}:{})},stopsByOrder:'paradas_por_op'in stops?stops.paradas_por_op||{}:{},timesByOrder:'tempos_por_op'in times?times.tempos_por_op||{}:{},occurrencesByOrder:'por_op'in occ?occ.por_op||{}:{}}}
export function linkSaleOrder(input:{codigo_pedido:number;codigo:string;quantidade_programado:number;numero_op:string;op_producao_id:number}){return post<{success:boolean}>('/api/producao/kanban-programacao',input)}
export function startProduction(input:ProductionActionInput){return post<{success:boolean}>('/api/producao/iniciar-producao',input)}
export function finishProductionStep(input:ProductionActionInput&{col_key:string;posto_atual:string;proximo_status:string;operacao:string}){return post<{success:boolean}>('/api/producao/finalizar-operacao',input)}
export function moveProductionBack(input:ProductionActionInput&{col_key:string}){return post<{success:boolean}>('/api/producao/retroceder-op',input)}
export function loadStopReasons(){return request<{success:boolean;motivos:Array<{id?:number;tipo_parada:string;motivo:string}>}>('/api/producao/paradas/motivos')}
export function createProductionStop(input:{kanban_programacao_id:number|null;numero_op:string;usuario:string;operacao:string;tipo_parada:string;motivo:string}){return post<{success:boolean;parada:ProductionStop}>('/api/producao/paradas',input)}
export function resumeProduction(stopId:number){return post<{success:boolean;parada:ProductionStop}>(`/api/producao/paradas/${stopId}/retomar`,{})}
