import { afterEach,describe,expect,it,vi } from 'vitest'
import { loadMovementPermission,loadStockOscillation,loadStockPosition,loadWarehouseAddress,loadWarehouseLocations,loadWarehouseOccupancy,loadWarehouseStock,parseBulkMovement,requestAdjustment,requestTransfer } from './warehouseGateway'
const response=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json'}})
afterEach(()=>vi.restoreAllMocks())
describe('warehouseGateway contracts',()=>{
 it('reads locations, stock and current permission with credentials',async()=>{const f=vi.spyOn(globalThis,'fetch').mockImplementation(async()=>response({ok:true,locais:[],dados:[],regra:null}));await loadWarehouseLocations();await loadWarehouseStock('107');await loadMovementPermission();expect(f.mock.calls.map(x=>x[0])).toEqual(['/api/armazem/locais','/api/armazem/almoxarifado','/api/movimentacoes/permissao-atual']);expect(f.mock.calls[1]![1]).toEqual(expect.objectContaining({method:'POST',body:JSON.stringify({pagina:1,local:'107'}),credentials:'include'}))})
 it('preserves transfer and adjustment payloads without a real request',async()=>{const f=vi.spyOn(globalThis,'fetch').mockImplementation(async()=>response({ok:true}));const item={codigo:'MP1',descricao:'Peça',qtd:2,cmc:4,codigo_produto:99,codOmie:99};const transfer={origem:'1',destino:'2',data_movimentacao:'2026-08-21',solicitante:'ana',itens:[item]};const adjustment={tipo_operacao:'SAI' as const,local_estoque:'1',data_movimentacao:'2026-08-21',motivo:'INV' as const,itens:[item]};await requestTransfer(transfer);await requestAdjustment(adjustment);expect(f.mock.calls[0]![0]).toBe('/api/transferencias');expect(f.mock.calls[0]![1]).toEqual(expect.objectContaining({body:JSON.stringify(transfer)}));expect(f.mock.calls[1]![0]).toBe('/api/ajustes');expect(f.mock.calls[1]![1]).toEqual(expect.objectContaining({body:JSON.stringify(adjustment)}))})
 it('preserves 3D, position and oscillation read contracts',async()=>{const f=vi.spyOn(globalThis,'fetch').mockImplementation(async()=>response({ok:true,ocupacao:{},itens:[],dados:[],rows:[]}));await loadWarehouseOccupancy();await loadWarehouseAddress('01-02-03-001');await loadStockPosition('2026-08-21',2);await loadStockOscillation('fluxo','custom','2026-08-01','2026-08-21');expect(f.mock.calls.map(x=>x[0])).toEqual(['/api/etiquetas/ocupacao','/api/etiquetas/ocupacao/detalhe?endereco=01-02-03-001','/api/estoque/posicao-por-data?data=2026-08-21&pagina=2&limite=200','/api/estoque/oscilacao-fluxo?data_de=2026-08-01&data_ate=2026-08-21'])})
 it('parses the three proven spreadsheet layouts',()=>{expect(parseBulkMovement('A\tENT\t10\t1\t2,5\nB\tTRF\t3\t1\t2\nC\t4')).toEqual([{line:1,code:'A',type:'ENT',quantity:10,warehouse:'1',cmc:2.5},{line:2,code:'B',type:'TRF',quantity:3,origin:'1',destination:'2',cmc:null},{line:3,code:'C',type:null,quantity:4,warehouse:null,cmc:null}])})
})
