import type { AdjustmentInput, BulkLine, MovementRule, OccupancyItem, StockOscillation, StockPosition, TransferInput, WarehouseLocation, WarehouseStock } from '../features/warehouses/types'
const base=import.meta.env.VITE_API_BASE_URL||''
export class WarehouseGatewayError extends Error { readonly status?:number; constructor(message:string,status?:number){super(message);this.status=status} }
async function request<T>(path:string,init:RequestInit={}){const headers=new Headers(init.headers);headers.set('Accept','application/json');if(init.body)headers.set('Content-Type','application/json');let response:Response;try{response=await fetch(`${base}${path}`,{...init,headers,credentials:'include',cache:'no-store'})}catch(e){throw new WarehouseGatewayError(e instanceof Error?e.message:'Falha de conexão.')}const raw=await response.text();let data:Record<string,unknown>={};try{data=raw?JSON.parse(raw):{}}catch{data={error:raw}}if(!response.ok||data.ok===false)throw new WarehouseGatewayError(typeof data.error==='string'?data.error:`Falha HTTP ${response.status}`,response.status);return data as T}
export function loadWarehouseLocations(force=false){return request<{ok:boolean;locais:WarehouseLocation[];fonte?:string}>(`/api/armazem/locais${force?'?force=1':''}`)}
export function loadWarehouseStock(local:string){return request<{ok:boolean;local:string;dados:WarehouseStock[]}>('/api/armazem/almoxarifado',{method:'POST',body:JSON.stringify({pagina:1,local})})}
export function loadMovementPermission(){return request<{ok:boolean;regra:MovementRule|null}>('/api/movimentacoes/permissao-atual')}
export function searchWarehouseProducts(query:string){return request<{data:Array<{codigo:string;descricao?:string}>}>(`/api/produtos/search?q=${encodeURIComponent(query.trim())}&limit=40`)}
export function requestTransfer(input:TransferInput){return request<{ok:boolean;ids?:number[]}>('/api/transferencias',{method:'POST',body:JSON.stringify(input)})}
export function requestAdjustment(input:AdjustmentInput){return request<{ok:boolean;ids?:number[]}>('/api/ajustes',{method:'POST',body:JSON.stringify(input)})}
export function loadWarehouseOccupancy(){return request<{ok:boolean;ocupacao:Record<string,OccupancyItem[]>}>('/api/etiquetas/ocupacao')}
export function loadWarehouseAddress(address:string){return request<{ok:boolean;itens:OccupancyItem[]}>(`/api/etiquetas/ocupacao/detalhe?endereco=${encodeURIComponent(address)}`)}
export function loadStockDates(){return request<{ok:boolean;datas:string[]}>('/api/estoque/datas-disponiveis')}
export function loadStockPosition(date:string,page=1){return request<{ok:boolean;dados:StockPosition[];pagina:number;totalPaginas:number;totalRegistros:number}>(`/api/estoque/posicao-por-data?data=${encodeURIComponent(date)}&pagina=${page}&limite=200`)}
export function loadStockOscillation(mode:'nivel'|'fluxo',period='30',from='',to=''){const params=new URLSearchParams();if(period==='custom'){params.set('data_de',from);params.set('data_ate',to)}else params.set('periodo',period);return request<{ok:boolean;rows:StockOscillation[];periodo?:{de?:string;ate?:string};aviso?:string}>(`/api/estoque/oscilacao-${mode}?${params}`)}
const parseNumber=(value:string)=>{const raw=value.trim().replace(/\s/g,'');if(!raw)return null;const normalized=raw.includes(',')?raw.replace(/\./g,'').replace(',','.'):raw;const parsed=Number(normalized);return Number.isFinite(parsed)?parsed:null}
export function parseBulkMovement(text:string):BulkLine[]{return text.split(/\r?\n/).map((raw,index)=>({raw:raw.trim(),line:index+1})).filter(x=>x.raw&&!x.raw.startsWith('#')).map(({raw,line})=>{const p=raw.split('\t').map(x=>x.trim());const type=p[1]?.toUpperCase();if(type==='TRF')return{line,code:p[0]||'',type:'TRF',quantity:parseNumber(p[2]||''),origin:p[3]||null,destination:p[4]||null,cmc:parseNumber(p[5]||'')};if(type==='ENT'||type==='SAI')return{line,code:p[0]||'',type,quantity:parseNumber(p[2]||''),warehouse:p[3]||null,cmc:parseNumber(p[4]||'')};return{line,code:p[0]||'',type:null,quantity:parseNumber(p[1]||''),warehouse:p[2]||null,cmc:parseNumber(p[3]||'')}})}
