-- Objetivo: Criar tabela configuracoes.familia para persistir dados de famílias do Omie
-- Permite edição local do ID e Tipo das famílias sem depender da API Omie

CREATE TABLE IF NOT EXISTS configuracoes.familia (
  -- ID editável pelo usuário (pode ser diferente do código Omie)
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  
  -- Código da família vindo do Omie (chave primária)
  codigo TEXT PRIMARY KEY,
  
  -- Nome da família vindo do Omie
  nome_familia TEXT NOT NULL,
  
  -- Tipo da família (editável pelo usuário)
  tipo TEXT,
  
  -- Timestamps para auditoria
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Índices para otimizar consultas
CREATE INDEX IF NOT EXISTS idx_familia_nome ON configuracoes.familia(nome_familia);
CREATE INDEX IF NOT EXISTS idx_familia_tipo ON configuracoes.familia(tipo);

-- Comentários explicativos
COMMENT ON TABLE configuracoes.familia IS 'Famílias de produtos sincronizadas do Omie com campos editáveis (id e tipo)';
COMMENT ON COLUMN configuracoes.familia.id IS 'ID editável pelo usuário - usado para organização interna';
COMMENT ON COLUMN configuracoes.familia.codigo IS 'Código original da família no Omie (imutável)';
COMMENT ON COLUMN configuracoes.familia.nome_familia IS 'Nome da família sincronizado do Omie';
COMMENT ON COLUMN configuracoes.familia.tipo IS 'Tipo da família - campo livre editável pelo usuário';
