import { render, screen } from '@testing-library/react'
import { describe, expect, it, vi } from 'vitest'
import { ProductListScreen } from './ProductListScreen'

vi.mock('../hooks/usePilotData', () => ({
  usePilotData: () => ({
    filtered: [
      {
        codigo_produto: 1,
        codigo_produto_integracao: null,
        codigo: '4237',
        descricao: 'Produto sem foto',
        descricao_familia: null,
        unidade: 'UN',
        tipoitem: null,
        ncm: null,
        valor_unitario: null,
        quantidade_estoque: 1,
        estoque_minimo: 0,
        saldo_almox: 1,
        saldo_expedicao: 0,
        saldo_enderecado: 0,
        abaixo_minimo: false,
        estoque_negativo: false,
        expedicao_negativa: false,
        saldo_endereco_sem_omie: false,
        saldo_divergente_endereco: false,
        diferenca_saldo_endereco: 0,
        item_limitado: false,
        inativo: null,
        bloqueado: null,
        marca: null,
        modelo: null,
        dalt: null,
        halt: null,
        dinc: null,
        hinc: null,
        primeira_imagem: null,
        compraStatus: null,
        purchaseState: 'sem_compra',
        origemCodigo: null,
        tipoCodigo: null,
        imageUrl: null,
        locaisPositivos: [],
        isInactive: false,
        isObsolete: false,
        isEngineering: false,
      },
    ],
    paginated: [
      {
        codigo_produto: 1,
        codigo_produto_integracao: null,
        codigo: '4237',
        descricao: 'Produto sem foto',
        descricao_familia: null,
        unidade: 'UN',
        tipoitem: null,
        ncm: null,
        valor_unitario: null,
        quantidade_estoque: 1,
        estoque_minimo: 0,
        saldo_almox: 1,
        saldo_expedicao: 0,
        saldo_enderecado: 0,
        abaixo_minimo: false,
        estoque_negativo: false,
        expedicao_negativa: false,
        saldo_endereco_sem_omie: false,
        saldo_divergente_endereco: false,
        diferenca_saldo_endereco: 0,
        item_limitado: false,
        inativo: null,
        bloqueado: null,
        marca: null,
        modelo: null,
        dalt: null,
        halt: null,
        dinc: null,
        hinc: null,
        primeira_imagem: null,
        compraStatus: null,
        purchaseState: 'sem_compra',
        origemCodigo: null,
        tipoCodigo: null,
        imageUrl: null,
        locaisPositivos: [],
        isInactive: false,
        isObsolete: false,
        isEngineering: false,
      },
    ],
    loading: false,
    error: null,
    warnings: [],
    filters: {
      search: '',
      families: [],
      typeItems: [],
      origins: [],
      purchaseStatus: [],
      locationCodes: [],
      showInactive: false,
      hideObsolete: false,
      hideEngineering: false,
      semEstoqueMin: false,
      abaixoEstoqueMin: false,
      acimaEstoqueMin: false,
      proximoEstoqueMin: false,
      proximoPercent: 10,
      estoqueNegativo: false,
      expedicaoNegativa: false,
      saldoEnderecoSemOmie: false,
      saldoDivergenteEndereco: false,
    },
    setFilters: vi.fn(),
    filtersMeta: { families: [], typeItems: [], locations: [] },
    page: 1,
    setPage: vi.fn(),
    pageCount: 1,
    pageSize: 50,
    viewMode: 'grid',
    setViewMode: vi.fn(),
    cartCount: 0,
    streamEvents: [],
    dataMode: 'proxy',
    reload: vi.fn(),
    fetchedAt: Date.now(),
  }),
}))

describe('ProductListScreen', () => {
  it('renders neutral placeholder when product has no image and hides "Não comprado ainda"', () => {
    render(
      <ProductListScreen
        permissions={{
          canOpenCart: true,
          canOpenSeparation: true,
          canEditCatalog: true,
          cartReason: null,
          separationReason: null,
        }}
      />,
    )

    expect(screen.getByLabelText('Produto 4237 sem imagem')).toBeInTheDocument()
    expect(screen.queryByText('Não comprado ainda')).not.toBeInTheDocument()
  })
})
