var OMIE_APP_KEY = 'PUT_YOUR_APP_KEY_HERE';
var OMIE_APP_SECRET = 'PUT_YOUR_APP_SECRET_HERE';

var XMLHttpRequest = require("xmlhttprequest").XMLHttpRequest;
var ProdutosEstruturaJsonClient=function(){
	this._EndPoint="https://app.omie.com.br/api/v1/geral/malha/";
	this._Call=function(method,param,cb){
		var server= new XMLHttpRequest();
		server.open("POST",this._EndPoint,cb!=null);
		server.setRequestHeader("Content-Type","application/json");
		var req=JSON.stringify({call:method,app_key:OMIE_APP_KEY,app_secret:OMIE_APP_SECRET,param:(param)?param:[]});
		if(cb){
			server.onreadystatechange=this._EndCall;
			server.cb=cb;
			server.send(req);
			return server;
		}else{
			server.send(req);
			var res=JSON.parse(server.responseText);
			delete(server);
			return res;
		}
	};
	this._EndCall=function(e){
		var server=this;
		if(server.readyState!=4)
			return;
		if(server.status!=200)
			throw(new Exception("AJAX error "+server.status+": "+server.statusText));
		server.cb(JSON.parse(server.responseText));
		server.cb=null;
		delete(server);
	};
	this.IncluirEstrutura=function(
		malhaIncluirRequest,
		_cb
	){
		return this._Call(
			"IncluirEstrutura",
			[
			malhaIncluirRequest
			],
			(_cb)?_cb:null
		);
	};
	this.AlterarEstrutura=function(
		malhaAlterarRequest,
		_cb
	){
		return this._Call(
			"AlterarEstrutura",
			[
			malhaAlterarRequest
			],
			(_cb)?_cb:null
		);
	};
	this.ExcluirEstrutura=function(
		malhaExcluirRequest,
		_cb
	){
		return this._Call(
			"ExcluirEstrutura",
			[
			malhaExcluirRequest
			],
			(_cb)?_cb:null
		);
	};
	this.ConsultarEstrutura=function(
		malhaConsultarRequest,
		_cb
	){
		return this._Call(
			"ConsultarEstrutura",
			[
			malhaConsultarRequest
			],
			(_cb)?_cb:null
		);
	};
	this.ListarEstruturas=function(
		malhaPesquisarRequest,
		_cb
	){
		return this._Call(
			"ListarEstruturas",
			[
			malhaPesquisarRequest
			],
			(_cb)?_cb:null
		);
	};
	this.custoProducao=function(){
		this.vMOD=null;
		this.vGGF=null;
	};
	this.ident=function(){
		this.idProduto=null;
		this.intProduto=null;
		this.codProduto=null;
		this.descrProduto=null;
		this.tipoProduto=null;
		this.idFamilia=null;
		this.codFamilia=null;
		this.descrFamilia=null;
		this.unidProduto=null;
		this.pesoLiqProduto=null;
		this.pesoBrutoProduto=null;
	};
	this.itemMalhaAlterar=function(){
		this.idMalha=null;
		this.intMalha=null;
		this.idProdMalha=null;
		this.intProdMalha=null;
		this.quantProdMalha=null;
		this.percPerdaProdMalha=null;
		this.obsProdMalha=null;
		this.codigo_local_estoque=null;
	};
	this.itemMalhaIncluir=function(){
		this.intMalha=null;
		this.idProdMalha=null;
		this.intProdMalha=null;
		this.quantProdMalha=null;
		this.percPerdaProdMalha=null;
		this.obsProdMalha=null;
		this.codigo_local_estoque=null;
	};
	this.itemMalhaStatus=function(){
		this.idProdMalha=null;
		this.intProdMalha=null;
		this.idMalha=null;
		this.intMalha=null;
		this.codStatus=null;
		this.descrStatus=null;
	};
	this.itens=function(){
		this.idMalha=null;
		this.intMalha=null;
		this.idProdMalha=null;
		this.intProdMalha=null;
		this.codProdMalha=null;
		this.descrProdMalha=null;
		this.quantProdMalha=null;
		this.unidProdMalha=null;
		this.tipoProdMalha=null;
		this.idFamMalha=null;
		this.codFamMalha=null;
		this.descrFamMalha=null;
		this.pesoLiqProdMalha=null;
		this.pesoBrutoProdMalha=null;
		this.percPerdaProdMalha=null;
		this.obsProdMalha=null;
		this.dIncProdMalha=null;
		this.hIncProdMalha=null;
		this.uIncProdMalha=null;
		this.dAltProdMalha=null;
		this.hAltProdMalha=null;
		this.uAltProdMalha=null;
	};
	this.malhaAlterarRequest=function(){
		this.idProduto=null;
		this.intProduto=null;
		this.itemMalhaAlterar=null;
	};
	this.malhaAlterarResponse=function(){
		this.idProduto=null;
		this.intProduto=null;
		this.codStatus=null;
		this.descrStatus=null;
		this.itemMalhaStatus=null;
	};
	this.malhaConsultarRequest=function(){
		this.idProduto=null;
		this.intProduto=null;
		this.codProduto=null;
	};
	this.malhaConsultarResponse=function(){
		this.ident=null;
		this.observacoes=null;
		this.custoProducao=null;
		this.itens=null;
	};
	this.observacoes=function(){
		this.obsRelevantes=null;
	};
	this.malhaExcluirRequest=function(){
		this.idProduto=null;
		this.intProduto=null;
		this.idMalha=null;
		this.intMalha=null;
	};
	this.malhaExcluirResponse=function(){
		this.idProduto=null;
		this.intProduto=null;
		this.idMalha=null;
		this.intMalha=null;
		this.codStatus=null;
		this.descrStatus=null;
	};
	this.malhaIncluirRequest=function(){
		this.idProduto=null;
		this.intProduto=null;
		this.itemMalhaIncluir=null;
	};
	this.malhaIncluirResponse=function(){
		this.idProduto=null;
		this.intProduto=null;
		this.codStatus=null;
		this.descrStatus=null;
		this.itemMalhaStatus=null;
	};
	this.malhaPesquisarRequest=function(){
		this.nPagina=null;
		this.nRegPorPagina=null;
		this.cOrdenarPor=null;
		this.dIncProdMalhaIni=null;
		this.dIncProdMalhaFim=null;
		this.hIncProdMalhaIni=null;
		this.hIncProdMalhaFim=null;
		this.dAltProdMalhaIni=null;
		this.dAltProdMalhaFim=null;
		this.hAltProdMalhaIni=null;
		this.hAltProdMalhaFim=null;
	};
	this.malhaPesquisarResponse=function(){
		this.nPagina=null;
		this.nTotPaginas=null;
		this.nRegistros=null;
		this.nTotRegistros=null;
		this.produtosEncontrados=null;
	};
	this.produtosEncontrados=function(){
		this.ident=null;
		this.observacoes=null;
		this.custoProducao=null;
		this.itens=null;
	};
	this.omie_fail=function(){
		this.code=null;
		this.description=null;
		this.referer=null;
		this.fatal=null;
	};
};
module.exports = ProdutosEstruturaJsonClient;