-- Migração: mover dados de public.familia para configuracoes.familia, se existir

CREATE SCHEMA IF NOT EXISTS configuracoes;

-- Garante tabela destino
CREATE TABLE IF NOT EXISTS configuracoes.familia (
  id            integer GENERATED BY DEFAULT AS IDENTITY,
  codigo        text PRIMARY KEY,
  nome_familia  text NOT NULL,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.tables
     WHERE table_schema='public' AND table_name='familia'
  ) THEN
    INSERT INTO configuracoes.familia (codigo, nome_familia, created_at, updated_at)
    SELECT f.codigo, f.nome_familia, COALESCE(f.created_at, now()), COALESCE(f.updated_at, now())
      FROM public.familia f
    ON CONFLICT (codigo) DO UPDATE
      SET nome_familia = EXCLUDED.nome_familia,
          updated_at   = now();
    -- opcional: manter tabela antiga ou dropar
    -- DROP TABLE public.familia;
  END IF;
END$$;

-- Trigger no novo schema
CREATE OR REPLACE FUNCTION configuracoes.familia_set_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger
     WHERE tgname = 'trg_familia_set_updated_at'
  ) THEN
    CREATE TRIGGER trg_familia_set_updated_at
    BEFORE UPDATE ON configuracoes.familia
    FOR EACH ROW EXECUTE FUNCTION configuracoes.familia_set_updated_at();
  END IF;
END$$;
