-- Criação do schema de configurações e da tabela de famílias (Omie)
-- Guarda o código e o nome da família retornados pela API

CREATE SCHEMA IF NOT EXISTS configuracoes;

CREATE TABLE IF NOT EXISTS configuracoes.familia (
  id            integer GENERATED BY DEFAULT AS IDENTITY,
  codigo        text PRIMARY KEY,
  nome_familia  text NOT NULL,
  tipo          text,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);

-- Trigger para atualizar updated_at automaticamente
CREATE OR REPLACE FUNCTION configuracoes.familia_set_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger
     WHERE tgname = 'trg_familia_set_updated_at'
  ) THEN
    CREATE TRIGGER trg_familia_set_updated_at
    BEFORE UPDATE ON configuracoes.familia
    FOR EACH ROW EXECUTE FUNCTION configuracoes.familia_set_updated_at();
  END IF;
END$$;
