var OMIE_APP_KEY = 'PUT_YOUR_APP_KEY_HERE';
var OMIE_APP_SECRET = 'PUT_YOUR_APP_SECRET_HERE';

var XMLHttpRequest = require("xmlhttprequest").XMLHttpRequest;
var PedidoCompraJsonClient=function(){
	this._EndPoint="https://app.omie.com.br/api/v1/produtos/pedidocompra/";
	this._Call=function(method,param,cb){
		var server= new XMLHttpRequest();
		server.open("POST",this._EndPoint,cb!=null);
		server.setRequestHeader("Content-Type","application/json");
		var req=JSON.stringify({call:method,app_key:OMIE_APP_KEY,app_secret:OMIE_APP_SECRET,param:(param)?param:[]});
		if(cb){
			server.onreadystatechange=this._EndCall;
			server.cb=cb;
			server.send(req);
			return server;
		}else{
			server.send(req);
			var res=JSON.parse(server.responseText);
			delete(server);
			return res;
		}
	};
	this._EndCall=function(e){
		var server=this;
		if(server.readyState!=4)
			return;
		if(server.status!=200)
			throw(new Exception("AJAX error "+server.status+": "+server.statusText));
		server.cb(JSON.parse(server.responseText));
		server.cb=null;
		delete(server);
	};
	this.IncluirPedCompra=function(
		com_pedido_incluir_request,
		_cb
	){
		return this._Call(
			"IncluirPedCompra",
			[
			com_pedido_incluir_request
			],
			(_cb)?_cb:null
		);
	};
	this.AlteraPedCompra=function(
		com_pedido_alterar_request,
		_cb
	){
		return this._Call(
			"AlteraPedCompra",
			[
			com_pedido_alterar_request
			],
			(_cb)?_cb:null
		);
	};
	this.ExcluirPedCompra=function(
		com_pedido_excluir_request,
		_cb
	){
		return this._Call(
			"ExcluirPedCompra",
			[
			com_pedido_excluir_request
			],
			(_cb)?_cb:null
		);
	};
	this.UpsertPedCompra=function(
		com_pedido_upsert_request,
		_cb
	){
		return this._Call(
			"UpsertPedCompra",
			[
			com_pedido_upsert_request
			],
			(_cb)?_cb:null
		);
	};
	this.ConsultarPedCompra=function(
		com_pedido_consultar_request,
		_cb
	){
		return this._Call(
			"ConsultarPedCompra",
			[
			com_pedido_consultar_request
			],
			(_cb)?_cb:null
		);
	};
	this.PesquisarPedCompra=function(
		com_pedido_pesquisar_request,
		_cb
	){
		return this._Call(
			"PesquisarPedCompra",
			[
			com_pedido_pesquisar_request
			],
			(_cb)?_cb:null
		);
	};
	this.cabecalho_alterar=function(){
		this.nCodPed=null;
		this.cCodIntPed=null;
		this.dDtPrevisao=null;
		this.cCodParc=null;
		this.nQtdeParc=null;
		this.cCnpjCpfFor=null;
		this.nCodFor=null;
		this.cCodIntFor=null;
		this.cCodCateg=null;
		this.nCodCompr=null;
		this.cContato=null;
		this.cContrato=null;
		this.nCodCC=null;
		this.nCodIntCC=null;
		this.nCodProj=null;
		this.cNumPedido=null;
		this.cObs=null;
		this.cObsInt=null;
	};
	this.cabecalho_consulta=function(){
		this.nCodPed=null;
		this.cCodIntPed=null;
		this.dIncData=null;
		this.cIncHora=null;
		this.cEtapa=null;
		this.cNumero=null;
		this.dDtPrevisao=null;
		this.cCodParc=null;
		this.nQtdeParc=null;
		this.nCodFor=null;
		this.cCodIntFor=null;
		this.cCodCateg=null;
		this.nCodCompr=null;
		this.cContato=null;
		this.cContrato=null;
		this.nCodCC=null;
		this.nCodIntCC=null;
		this.nCodProj=null;
		this.cNumPedido=null;
		this.cObs=null;
		this.cObsInt=null;
	};
	this.cabecalho_incluir=function(){
		this.cCodIntPed=null;
		this.dDtPrevisao=null;
		this.cCodParc=null;
		this.nQtdeParc=null;
		this.cCnpjCpfFor=null;
		this.nCodFor=null;
		this.cCodIntFor=null;
		this.cCodCateg=null;
		this.nCodCompr=null;
		this.cContato=null;
		this.cContrato=null;
		this.nCodCC=null;
		this.nCodIntCC=null;
		this.nCodProj=null;
		this.cNumPedido=null;
		this.cObs=null;
		this.cObsInt=null;
		this.cEmailAprovador=null;
	};
	this.cabecalho_upsert=function(){
		this.nCodPed=null;
		this.cCodIntPed=null;
		this.dDtPrevisao=null;
		this.cCodParc=null;
		this.nQtdeParc=null;
		this.cCnpjCpfFor=null;
		this.nCodFor=null;
		this.cCodIntFor=null;
		this.cCodCateg=null;
		this.nCodCompr=null;
		this.cContato=null;
		this.cContrato=null;
		this.nCodCC=null;
		this.nCodIntCC=null;
		this.nCodProj=null;
		this.cNumPedido=null;
		this.cObs=null;
		this.cObsInt=null;
		this.cEmailAprovador=null;
	};
	this.com_pedido_alterar_request=function(){
		this.cabecalho_alterar=null;
		this.frete_alterar=null;
		this.produtos_alterar=null;
		this.departamentos_alterar=null;
		this.parcelas_alterar=null;
	};
	this.frete_alterar=function(){
		this.nCodTransp=null;
		this.cCodIntTransp=null;
		this.cTpFrete=null;
		this.cPlaca=null;
		this.cUF=null;
		this.nQtdVol=null;
		this.cEspVol=null;
		this.cMarVol=null;
		this.cNumVol=null;
		this.nPesoLiq=null;
		this.nPesoBruto=null;
		this.nValFrete=null;
		this.nValSeguro=null;
		this.cLacre=null;
		this.nValOutras=null;
	};
	this.produtos_alterar=function(){
		this.cCodIntItem=null;
		this.nCodItem=null;
		this.cCodIntProd=null;
		this.nCodProd=null;
		this.cProduto=null;
		this.cDescricao=null;
		this.cNCM=null;
		this.cUnidade=null;
		this.cEAN=null;
		this.nPesoLiq=null;
		this.nPesoBruto=null;
		this.nQtde=null;
		this.nValUnit=null;
		this.nDesconto=null;
		this.nValorIcms=null;
		this.nValorSt=null;
		this.nValorIpi=null;
		this.nValorPis=null;
		this.nValorCofins=null;
		this.cObs=null;
		this.cMkpAtuPv=null;
		this.cMkpAtuSm=null;
		this.nMkpPerc=null;
		this.codigo_local_estoque=null;
		this.cCodCateg=null;
	};
	this.departamentos_alterar=function(){
		this.cCodDepto=null;
		this.nPerc=null;
	};
	this.parcelas_alterar=function(){
		this.nParcela=null;
		this.dVencto=null;
		this.nValor=null;
		this.nDias=null;
		this.nPercent=null;
		this.cTipoDoc=null;
	};
	this.com_pedido_alterar_response=function(){
		this.nCodPed=null;
		this.cCodIntPed=null;
		this.cCodStatus=null;
		this.cDescStatus=null;
		this.cNumero=null;
	};
	this.com_pedido_consultar_request=function(){
		this.nCodPed=null;
		this.cCodIntPed=null;
		this.cNumero=null;
	};
	this.com_pedido_excluir_request=function(){
		this.nCodPed=null;
		this.cCodIntPed=null;
	};
	this.com_pedido_excluir_response=function(){
		this.nCodPed=null;
		this.cCodIntPed=null;
		this.cCodStatus=null;
		this.cDescStatus=null;
	};
	this.com_pedido_incluir_request=function(){
		this.cabecalho_incluir=null;
		this.frete_incluir=null;
		this.produtos_incluir=null;
		this.departamentos_incluir=null;
		this.parcelas_incluir=null;
	};
	this.frete_incluir=function(){
		this.nCodTransp=null;
		this.cCodIntTransp=null;
		this.cTpFrete=null;
		this.cPlaca=null;
		this.cUF=null;
		this.nQtdVol=null;
		this.cEspVol=null;
		this.cMarVol=null;
		this.cNumVol=null;
		this.nPesoLiq=null;
		this.nPesoBruto=null;
		this.nValFrete=null;
		this.nValSeguro=null;
		this.cLacre=null;
		this.nValOutras=null;
	};
	this.produtos_incluir=function(){
		this.cCodIntItem=null;
		this.cCodIntProd=null;
		this.nCodProd=null;
		this.cProduto=null;
		this.cDescricao=null;
		this.cNCM=null;
		this.cUnidade=null;
		this.cEAN=null;
		this.nPesoLiq=null;
		this.nPesoBruto=null;
		this.nQtde=null;
		this.nValUnit=null;
		this.nDesconto=null;
		this.nValorIcms=null;
		this.nValorSt=null;
		this.nValorIpi=null;
		this.nValorPis=null;
		this.nValorCofins=null;
		this.cObs=null;
		this.cMkpAtuPv=null;
		this.cMkpAtuSm=null;
		this.nMkpPerc=null;
		this.codigo_local_estoque=null;
		this.cCodCateg=null;
	};
	this.departamentos_incluir=function(){
		this.cCodDepto=null;
		this.nPerc=null;
	};
	this.parcelas_incluir=function(){
		this.nParcela=null;
		this.dVencto=null;
		this.nValor=null;
		this.nDias=null;
		this.nPercent=null;
		this.cTipoDoc=null;
	};
	this.com_pedido_incluir_response=function(){
		this.nCodPed=null;
		this.cCodIntPed=null;
		this.cCodStatus=null;
		this.cDescStatus=null;
		this.cNumero=null;
	};
	this.com_pedido_pesquisar_request=function(){
		this.nPagina=null;
		this.nRegsPorPagina=null;
		this.lApenasImportadoApi=null;
		this.lExibirPedidosPendentes=null;
		this.lExibirPedidosFaturados=null;
		this.lExibirPedidosRecebidos=null;
		this.lExibirPedidosCancelados=null;
		this.lExibirPedidosEncerrados=null;
		this.lExibirPedidosRecParciais=null;
		this.lExibirPedidosFatParciais=null;
		this.dDataInicial=null;
		this.dDataFinal=null;
		this.lApenasAlterados=null;
	};
	this.com_pedido_pesquisar_response=function(){
		this.nPagina=null;
		this.nRegsPorPagina=null;
		this.lApenasImportadoApi=null;
		this.lExibirPedidosPendentes=null;
		this.lExibirPedidosFaturados=null;
		this.lExibirPedidosRecebidos=null;
		this.lExibirPedidosCancelados=null;
		this.lExibirPedidosEncerrados=null;
		this.dDataInicial=null;
		this.dDataFinal=null;
		this.nTotalPaginas=null;
		this.nTotalRegistros=null;
		this.pedidos_pesquisa=null;
	};
	this.pedidos_pesquisa=function(){
		this.cabecalho_consulta=null;
		this.frete_consulta=null;
		this.produtos_consulta=null;
		this.parcelas_consulta=null;
		this.departamentos_consulta=null;
	};
	this.com_pedido_upsert_request=function(){
		this.cabecalho_upsert=null;
		this.frete_upsert=null;
		this.produtos_upsert=null;
		this.departamentos_upsert=null;
		this.parcelas_upsert=null;
	};
	this.frete_upsert=function(){
		this.nCodTransp=null;
		this.cCodIntTransp=null;
		this.cTpFrete=null;
		this.cPlaca=null;
		this.cUF=null;
		this.nQtdVol=null;
		this.cEspVol=null;
		this.cMarVol=null;
		this.cNumVol=null;
		this.nPesoLiq=null;
		this.nPesoBruto=null;
		this.nValFrete=null;
		this.nValSeguro=null;
		this.cLacre=null;
		this.nValOutras=null;
	};
	this.produtos_upsert=function(){
		this.cCodIntItem=null;
		this.nCodItem=null;
		this.cCodIntProd=null;
		this.nCodProd=null;
		this.cProduto=null;
		this.cDescricao=null;
		this.cNCM=null;
		this.cUnidade=null;
		this.cEAN=null;
		this.nPesoLiq=null;
		this.nPesoBruto=null;
		this.nQtde=null;
		this.nValUnit=null;
		this.nDesconto=null;
		this.nValorIcms=null;
		this.nValorSt=null;
		this.nValorIpi=null;
		this.nValorPis=null;
		this.nValorCofins=null;
		this.cObs=null;
		this.cMkpAtuPv=null;
		this.cMkpAtuSm=null;
		this.nMkpPerc=null;
		this.codigo_local_estoque=null;
		this.cCodCateg=null;
	};
	this.departamentos_upsert=function(){
		this.cCodDepto=null;
		this.nPerc=null;
	};
	this.parcelas_upsert=function(){
		this.nParcela=null;
		this.dVencto=null;
		this.nValor=null;
		this.nDias=null;
		this.nPercent=null;
		this.cTipoDoc=null;
	};
	this.com_pedido_upsert_response=function(){
		this.nCodPed=null;
		this.cCodIntPed=null;
		this.cCodStatus=null;
		this.cDescStatus=null;
		this.cNumero=null;
	};
	this.departamentos_consulta=function(){
		this.cCodDepto=null;
		this.nPerc=null;
		this.nValor=null;
	};
	this.frete_consulta=function(){
		this.nCodTransp=null;
		this.cCodIntTransp=null;
		this.cTpFrete=null;
		this.cPlaca=null;
		this.cUF=null;
		this.nQtdVol=null;
		this.cEspVol=null;
		this.cMarVol=null;
		this.cNumVol=null;
		this.nPesoLiq=null;
		this.nPesoBruto=null;
		this.nValFrete=null;
		this.nValSeguro=null;
		this.cLacre=null;
		this.nValOutras=null;
	};
	this.parcelas_consulta=function(){
		this.nParcela=null;
		this.dVencto=null;
		this.nValor=null;
		this.nDias=null;
		this.nPercent=null;
		this.cTipoDoc=null;
	};
	this.produtos_consulta=function(){
		this.cCodIntItem=null;
		this.nCodItem=null;
		this.cCodIntProd=null;
		this.nCodProd=null;
		this.cProduto=null;
		this.cDescricao=null;
		this.cNCM=null;
		this.cEAN=null;
		this.cUnidade=null;
		this.nPesoLiq=null;
		this.nPesoBruto=null;
		this.nQtde=null;
		this.nValUnit=null;
		this.nValMerc=null;
		this.nDesconto=null;
		this.nValorIcms=null;
		this.nValorSt=null;
		this.nValorIpi=null;
		this.nValorPis=null;
		this.nValorCofins=null;
		this.nFrete=null;
		this.nSeguro=null;
		this.nDespesas=null;
		this.nValTot=null;
		this.cObs=null;
		this.cMkpAtuPv=null;
		this.cMkpAtuSm=null;
		this.nMkpPerc=null;
		this.codigo_local_estoque=null;
		this.cCodCateg=null;
		this.nQtdeRec=null;
	};
	this.omie_fail=function(){
		this.code=null;
		this.description=null;
		this.referer=null;
		this.fatal=null;
	};
};
module.exports = PedidoCompraJsonClient;