var OMIE_APP_KEY = 'PUT_YOUR_APP_KEY_HERE';
var OMIE_APP_SECRET = 'PUT_YOUR_APP_SECRET_HERE';

var XMLHttpRequest = require("xmlhttprequest").XMLHttpRequest;
var RecebimentoNFeJsonClient=function(){
	this._EndPoint="https://app.omie.com.br/api/v1/produtos/recebimentonfe/";
	this._Call=function(method,param,cb){
		var server= new XMLHttpRequest();
		server.open("POST",this._EndPoint,cb!=null);
		server.setRequestHeader("Content-Type","application/json");
		var req=JSON.stringify({call:method,app_key:OMIE_APP_KEY,app_secret:OMIE_APP_SECRET,param:(param)?param:[]});
		if(cb){
			server.onreadystatechange=this._EndCall;
			server.cb=cb;
			server.send(req);
			return server;
		}else{
			server.send(req);
			var res=JSON.parse(server.responseText);
			delete(server);
			return res;
		}
	};
	this._EndCall=function(e){
		var server=this;
		if(server.readyState!=4)
			return;
		if(server.status!=200)
			throw(new Exception("AJAX error "+server.status+": "+server.statusText));
		server.cb(JSON.parse(server.responseText));
		server.cb=null;
		delete(server);
	};
	this.ConcluirRecebimento=function(
		rcbtoConcluirRequest,
		_cb
	){
		return this._Call(
			"ConcluirRecebimento",
			[
			rcbtoConcluirRequest
			],
			(_cb)?_cb:null
		);
	};
	this.AlterarEtapaRecebimento=function(
		rcbtoAlterarEtapaRequest,
		_cb
	){
		return this._Call(
			"AlterarEtapaRecebimento",
			[
			rcbtoAlterarEtapaRequest
			],
			(_cb)?_cb:null
		);
	};
	this.ConsultarRecebimento=function(
		rcbtoConsultarRequest,
		_cb
	){
		return this._Call(
			"ConsultarRecebimento",
			[
			rcbtoConsultarRequest
			],
			(_cb)?_cb:null
		);
	};
	this.ListarRecebimentos=function(
		rcbtoListarRequest,
		_cb
	){
		return this._Call(
			"ListarRecebimentos",
			[
			rcbtoListarRequest
			],
			(_cb)?_cb:null
		);
	};
	this.ReverterRecebimento=function(
		rcbtoReverterRequest,
		_cb
	){
		return this._Call(
			"ReverterRecebimento",
			[
			rcbtoReverterRequest
			],
			(_cb)?_cb:null
		);
	};
	this.AlterarRecebimento=function(
		rcbtoAlterarRequest,
		_cb
	){
		return this._Call(
			"AlterarRecebimento",
			[
			rcbtoAlterarRequest
			],
			(_cb)?_cb:null
		);
	};
	this.ExcluirRecebimento=function(
		rcbtoExcluirRequest,
		_cb
	){
		return this._Call(
			"ExcluirRecebimento",
			[
			rcbtoExcluirRequest
			],
			(_cb)?_cb:null
		);
	};
	this.AlterarRecebimentoConcluido=function(
		rcbtoConcAlterarRequest,
		_cb
	){
		return this._Call(
			"AlterarRecebimentoConcluido",
			[
			rcbtoConcAlterarRequest
			],
			(_cb)?_cb:null
		);
	};
	this.cabec=function(){
		this.nIdReceb=null;
		this.nIdFornecedor=null;
		this.cPessoaFisica=null;
		this.cNome=null;
		this.cRazaoSocial=null;
		this.cInscricao=null;
		this.cCNPJ_CPF=null;
		this.cChaveNfe=null;
		this.cEtapa=null;
		this.cNumeroNFe=null;
		this.cSerieNFe=null;
		this.cModeloNFe=null;
		this.dEmissaoNFe=null;
		this.nValorNFe=null;
		this.cAmbienteNFe=null;
		this.cNaturezaOperacao=null;
	};
	this.categorias=function(){
		this.cCategoria=null;
		this.vCategoria=null;
		this.pCategoria=null;
	};
	this.cteCfopEntrada=function(){
		this.cCFOPEntrada=null;
	};
	this.departamentos=function(){
		this.cCodDepartamento=null;
		this.vDepartamento=null;
		this.pDepartamento=null;
	};
	this.ide=function(){
		this.nIdReceb=null;
		this.cChaveNfe=null;
	};
	this.infoAdicionais=function(){
		this.cCategCompra=null;
		this.nIdConta=null;
		this.dRegistro=null;
		this.nIdComprador=null;
		this.nIdProjeto=null;
	};
	this.infoCadastro=function(){
		this.dInc=null;
		this.hInc=null;
		this.cUsuarioInc=null;
		this.dAlt=null;
		this.hAlt=null;
		this.cUsuarioAlt=null;
		this.cFaturado=null;
		this.dFat=null;
		this.hFat=null;
		this.cUsuarioFat=null;
		this.cDevolvido=null;
		this.cDevolvidoParc=null;
		this.dDev=null;
		this.hDev=null;
		this.cUsuarioDev=null;
		this.cRecebido=null;
		this.dRec=null;
		this.hRec=null;
		this.cUsuarioRec=null;
		this.cAutorizado=null;
		this.cBloqueado=null;
		this.cCancelada=null;
		this.dCanc=null;
		this.hCanc=null;
		this.cUsuarioCanc=null;
		this.cDenegado=null;
		this.cOperacao=null;
	};
	this.itensAjustes=function(){
		this.cNaoGerarFinanceiro=null;
		this.cNaoGerarMovEstoque=null;
		this.nQtdeRecebida=null;
		this.codigo_local_estoque=null;
		this.cUnidade=null;
		this.cCFOPEntrada=null;
		this.itensSitTribEnt=null;
	};
	this.itensSitTribEnt=function(){
		this.cSitTribICMSE=null;
		this.cSitTribIPIE=null;
		this.cSitTribPISE=null;
		this.cSitTribCOFINSE=null;
		this.nBCPISE=null;
		this.nAliqPISE=null;
		this.nValPISE=null;
		this.nBCCOFINSE=null;
		this.nAliqCOFINSE=null;
		this.nValCOFINSE=null;
		this.cNaoCredICMSE=null;
		this.itensSitTribICMSSTEnt=null;
	};
	this.itensAtualPreco=function(){
		this.cAtualizarAtuPre=null;
		this.nPercAtuPre=null;
		this.cAtualizarMaiorAtuPre=null;
	};
	this.itensCabec=function(){
		this.nIdItem=null;
		this.nIdPedido=null;
		this.nIdItPedido=null;
		this.nIdProduto=null;
		this.nSequencia=null;
		this.cCodigoProduto=null;
		this.cDescricaoProduto=null;
		this.cIgnorarItem=null;
		this.cAdicionarNovo=null;
		this.cAssociarExistente=null;
		this.cItemDevolvido=null;
		this.cNCM=null;
		this.cEAN=null;
		this.cCFOP=null;
		this.nQtdeNFe=null;
		this.cUnidadeNfe=null;
		this.nPrecoUnit=null;
		this.vDesconto=null;
		this.vFrete=null;
		this.vTotalItem=null;
	};
	this.itensCOFINS=function(){
		this.cSitTribCOFINS=null;
		this.cTpCalcCOFINS=null;
		this.nBCCOFINS=null;
		this.nAliqCOFINS=null;
		this.nQtdUTCOFINS=null;
		this.nVaCOFINSSUT=null;
		this.nValCOFINS=null;
	};
	this.itensCustoEstoque=function(){
		this.cICMSCusto=null;
		this.cPISCusto=null;
		this.cICMSSTCusto=null;
		this.cCOFINSCusto=null;
		this.cIPICusto=null;
		this.cFreteCusto=null;
		this.cSeguroCusto=null;
		this.cOutrosDespCusto=null;
		this.nValorICMSSTCusto=null;
		this.nAliqCredPISCusto=null;
		this.nAliqCredCOFINSCusto=null;
	};
	this.itensICMS=function(){
		this.cSitTrib=null;
		this.cOrigem=null;
		this.cModBC=null;
		this.nRedBC=null;
		this.nBC=null;
		this.nAliq=null;
		this.nValor=null;
		this.nBCStRecAnt=null;
		this.nAliqStRecAnt=null;
		this.nValorStRecAnt=null;
		this.nPercDif=null;
		this.nValorDif=null;
		this.nValorSubst=null;
		this.nValorOpProp=null;
	};
	this.itensICMSSN=function(){
		this.cSitTribSN=null;
		this.cOrigem=null;
		this.nBCSNST=null;
		this.nValorSNST=null;
		this.nAliqCredSN=null;
		this.nCredSN=null;
		this.cModBCSN=null;
		this.nAliqRedBCSN=null;
		this.nBCSN=null;
		this.nAliqSN=null;
		this.nValorSN=null;
	};
	this.itensICMSST=function(){
		this.cModBCST=null;
		this.nMargVrAd=null;
		this.nRedBCST=null;
		this.nBCST=null;
		this.nAliqST=null;
		this.nAliqOP=null;
		this.nValorST=null;
		this.cCEST=null;
	};
	this.itensIde=function(){
		this.nSequencia=null;
		this.cAcao=null;
		this.nIdProdutoExistente=null;
		this.nIdPedidoExistente=null;
		this.nIdItPedidoExistente=null;
	};
	this.itensInfoAdic=function(){
		this.nPesoLiquidoIt=null;
		this.nPesoBrutoIt=null;
		this.cCategoriaItem=null;
		this.nNumPedCompra=null;
		this.cNumItPedCompra=null;
		this.cNumFCI=null;
		this.vAproxTributosIt=null;
		this.codigo_local_estoque_saida=null;
	};
	this.itensInfoAdicEditar=function(){
		this.cCategoriaItem=null;
		this.codigo_local_estoque_saida=null;
	};
	this.itensIPI=function(){
		this.cSitTribIPI=null;
		this.cTpCalcIPI=null;
		this.nBCIPI=null;
		this.nAliqIPI=null;
		this.nQtdUTIPI=null;
		this.nValIPIUT=null;
		this.cEnqIPI=null;
		this.nValIPI=null;
		this.nValIPIDev=null;
	};
	this.itensPIS=function(){
		this.cSitTribPIS=null;
		this.cTpCalcPIS=null;
		this.nBCPIS=null;
		this.nAliqPIS=null;
		this.nQtdUTPIS=null;
		this.nValPISUT=null;
		this.nValPIS=null;
	};
	this.itensRecebimento=function(){
		this.itensCabec=null;
		this.itensAjustes=null;
		this.itensInfoAdic=null;
		this.itensICMS=null;
		this.itensICMSST=null;
		this.itensICMSSN=null;
		this.itensIPI=null;
		this.itensCOFINS=null;
		this.itensPIS=null;
		this.itensAtualPreco=null;
		this.itensCustoEstoque=null;
	};
	this.itensRecebimentoEditar=function(){
		this.itensIde=null;
		this.itensAjustes=null;
		this.itensInfoAdicEditar=null;
		this.itensAtualPreco=null;
		this.itensCustoEstoque=null;
		this.lote_validade=null;
	};
	this.lote_validade=function(){
		this.nIdLote=null;
		this.nQtdLote=null;
		this.cNumLote=null;
		this.cCodAgreg=null;
		this.dDataFab=null;
		this.dDataVal=null;
	};
	this.itensSitTribICMSSTEnt=function(){
		this.nMargVrAdE=null;
		this.nRedBCSTE=null;
		this.nBCSTE=null;
		this.nAliqSTE=null;
		this.nValorST=null;
		this.nBCFCPE=null;
		this.nAliqFCPE=null;
		this.nValorFCPE=null;
	};
	this.observacoes=function(){
		this.cObs=null;
	};
	this.parcelas=function(){
		this.cCodParcela=null;
		this.nQtdParcela=null;
		this.parcelasLista=null;
	};
	this.parcelasLista=function(){
		this.dVencimento=null;
		this.nIdTitulo=null;
		this.nSequencia=null;
		this.vParcela=null;
		this.pParcela=null;
		this.cTipoDocumento=null;
		this.cFormaPagamento=null;
	};
	this.parcelasEditar=function(){
		this.cCodParcela=null;
		this.nQtdParcela=null;
		this.parcelasListaEditar=null;
	};
	this.parcelasListaEditar=function(){
		this.dVencimento=null;
		this.nSequencia=null;
		this.vParcela=null;
		this.pParcela=null;
	};
	this.rcbtoAlterarEtapaRequest=function(){
		this.nIdReceb=null;
		this.cChaveNfe=null;
		this.cEtapa=null;
	};
	this.rcbtoAlterarEtapaResponse=function(){
		this.nIdReceb=null;
		this.cCodStatus=null;
		this.cDescStatus=null;
	};
	this.rcbtoAlterarRequest=function(){
		this.ide=null;
		this.parcelasEditar=null;
		this.departamentos=null;
		this.infoAdicionais=null;
		this.itensRecebimentoEditar=null;
		this.observacoes=null;
		this.cteCfopEntrada=null;
	};
	this.rcbtoAlterarResponse=function(){
		this.nIdReceb=null;
		this.cCodStatus=null;
		this.cDescStatus=null;
	};
	this.rcbtoConcAlterarRequest=function(){
		this.ide=null;
		this.infoAdicionais=null;
	};
	this.rcbtoConcAlterarResponse=function(){
		this.nIdReceb=null;
		this.cCodStatus=null;
		this.cDescStatus=null;
	};
	this.rcbtoConcluirRequest=function(){
		this.nIdReceb=null;
		this.cChaveNfe=null;
		this.cEtapa=null;
	};
	this.rcbtoConcluirResponse=function(){
		this.nIdReceb=null;
		this.cCodStatus=null;
		this.cDescStatus=null;
	};
	this.rcbtoConsultarRequest=function(){
		this.nIdReceb=null;
		this.cChaveNfe=null;
	};
	this.rcbtoConsultarResponse=function(){
		this.cabec=null;
		this.itensRecebimento=null;
		this.infoAdicionais=null;
		this.transporte=null;
		this.totais=null;
		this.parcelas=null;
		this.departamentos=null;
		this.categorias=null;
		this.infoCadastro=null;
		this.observacoes=null;
		this.cteCfopEntrada=null;
	};
	this.transporte=function(){
		this.cTipoFrete=null;
		this.nIdTransportador=null;
		this.nQtdeVolume=null;
		this.cEspecieVolume=null;
		this.cMarcaVolume=null;
		this.cNumeroVolume=null;
		this.nPesoLiquido=null;
		this.nPesoBruto=null;
		this.cNumeroLacre=null;
		this.cPlacaVeiculo=null;
		this.cUFVeiculo=null;
		this.cRNTRC=null;
		this.cNomeTransp=null;
		this.cRazaoTransp=null;
		this.cCnpjCpfTransp=null;
	};
	this.totais=function(){
		this.bcICMS=null;
		this.vICMS=null;
		this.vICMSDesonerado=null;
		this.bcICMSST=null;
		this.vICMSSubstituicao=null;
		this.vTotalProdutos=null;
		this.vFrete=null;
		this.vSeguro=null;
		this.vOutrasDespesas=null;
		this.vTotalIPI=null;
		this.vTotalNFe=null;
		this.vTotalDescontos=null;
		this.vTotalPIS=null;
		this.vTotalCOFINS=null;
		this.vAproxTributos=null;
	};
	this.rcbtoExcluirRequest=function(){
		this.nIdReceb=null;
	};
	this.rcbtoExcluirResponse=function(){
		this.nIdReceb=null;
		this.cCodStatus=null;
		this.cDescStatus=null;
	};
	this.rcbtoListarRequest=function(){
		this.nPagina=null;
		this.nRegistrosPorPagina=null;
		this.cOrdenarPor=null;
		this.dtAltDe=null;
		this.dtAltAte=null;
		this.hrAltDe=null;
		this.hrAltAte=null;
		this.dtEmissaoDe=null;
		this.dtEmissaoAte=null;
		this.nIdFornecedor=null;
		this.cEtapa=null;
		this.cExibirDetalhes=null;
	};
	this.rcbtoListarResponse=function(){
		this.nPagina=null;
		this.nTotalPaginas=null;
		this.nRegistros=null;
		this.nTotalRegistros=null;
		this.recebimentos=null;
	};
	this.recebimentos=function(){
		this.cabec=null;
		this.itensRecebimento=null;
		this.infoAdicionais=null;
		this.transporte=null;
		this.totais=null;
		this.parcelas=null;
		this.departamentos=null;
		this.categorias=null;
		this.infoCadastro=null;
		this.observacoes=null;
	};
	this.rcbtoReverterRequest=function(){
		this.nIdReceb=null;
		this.cChaveNfe=null;
		this.cEtapa=null;
	};
	this.rcbtoReverterResponse=function(){
		this.nIdReceb=null;
		this.cCodStatus=null;
		this.cDescStatus=null;
	};
	this.omie_fail=function(){
		this.code=null;
		this.description=null;
		this.referer=null;
		this.fatal=null;
	};
};
module.exports = RecebimentoNFeJsonClient;