import { Eye, RefreshCw, Search, X } from 'lucide-react'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { loadRequesterSeparationKanban, loadSeparationItems } from '../../services/separationGateway'
import type { SeparationItem, SeparationKanbanCard } from './types'

const columns = [
  ['pendente', 'Solicitado'], ['Stund-by', 'Stand-by'], ['Separação', 'Em separação'], ['Separado', 'Separado'],
  ['Aguardando retirada', 'Aguardando retirada'], ['Concluído', 'Concluído'], ['Devolvido', 'Devolvido'],
] as const
const normalized = (value: unknown) => String(value || '').normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase()

export function RequesterSeparationScreen() {
  const [data, setData] = useState<Record<string, SeparationKanbanCard[]>>({})
  const [query, setQuery] = useState(''); const [active, setActive] = useState('pendente')
  const [selected, setSelected] = useState<SeparationKanbanCard | null>(null); const [items, setItems] = useState<SeparationItem[]>([])
  const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const reload = useCallback(async () => { setLoading(true); setError(''); try { setData((await loadRequesterSeparationKanban()).colunas || {}) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Falha ao carregar suas solicitações.') } finally { setLoading(false) } }, [])
  // oxlint-disable-next-line react/set-state-in-effect -- sincroniza o quadro autorizado da sessão no carregamento
  useEffect(() => { void reload() }, [reload])
  const filtered = useMemo(() => Object.fromEntries(columns.map(([key]) => [key, (data[key] || []).filter((card) => !query.trim() || normalized(JSON.stringify(card)).includes(normalized(query))) ])), [data, query])
  const open = async (card: SeparationKanbanCard) => { setSelected(card); setItems([]); try { setItems((await loadSeparationItems(card.n_solic, { includeDerived: true })).itens || []) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Falha ao abrir a SEP.') } }
  return <section><header className="mb-4 flex flex-col gap-3 border-b border-slate-200 pb-4 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-xl font-bold text-thermo-navy">Minhas solicitações</h1><p className="text-sm text-slate-600">Acompanhamento somente das SEPs autorizadas para a sua sessão.</p></div><button className="thermo-button thermo-button-secondary" onClick={() => void reload()} type="button"><RefreshCw className="size-4" />Atualizar</button></header>
    <label className="relative mb-4 block"><span className="sr-only">Buscar nas minhas solicitações</span><Search className="absolute left-3 top-3.5 size-4 text-slate-400" /><input className="min-h-11 w-full rounded-md border border-slate-300 bg-white pl-10 pr-3" onChange={(event) => setQuery(event.target.value)} placeholder="Buscar SEP ou item" value={query} /></label>
    {error && <div className="mb-4 rounded-md border border-red-200 bg-red-50 p-3 text-sm text-red-800" role="alert">{error}</div>}{loading ? <p className="rounded-md border bg-white p-8 text-center">Carregando…</p> : <><div className="mb-3 grid grid-cols-2 gap-2 sm:grid-cols-4 lg:hidden">{columns.map(([key, label]) => <button aria-selected={active === key} className={`min-h-11 rounded-md border px-2 text-xs font-semibold ${active === key ? 'bg-thermo-navy text-white' : 'bg-white'}`} key={key} onClick={() => setActive(key)} type="button">{label} ({filtered[key]?.length || 0})</button>)}</div><div className="overflow-x-auto pb-3"><div className="grid gap-3 lg:min-w-[106rem] lg:grid-cols-7">{columns.map(([key, label]) => <section className={`${active === key ? 'block' : 'hidden lg:block'} rounded-md border bg-slate-50`} key={key}><h2 className="border-b bg-white p-3 text-xs font-bold">{label} ({filtered[key]?.length || 0})</h2><div className="space-y-2 p-2">{(filtered[key] || []).map((card) => <button className="w-full rounded-md border bg-white p-3 text-left" key={card.n_solic} onClick={() => void open(card)} type="button"><b className="font-mono text-xs">{card.n_solic}</b><span className="mt-1 block text-xs text-slate-600">{card.total_itens} item(ns)</span><span className="mt-2 inline-flex items-center gap-1 text-xs font-semibold text-thermo-navy"><Eye className="size-3" />Acompanhar</span></button>)}</div></section>)}</div></div></>}
    {selected && <div className="fixed inset-0 z-50 flex items-end bg-slate-950/55 sm:items-center sm:justify-center sm:p-4"><section className="max-h-[92dvh] w-full overflow-y-auto rounded-t-lg bg-white p-4 sm:max-w-3xl sm:rounded-lg" role="dialog" aria-modal="true"><header className="mb-4 flex items-start justify-between"><div><b className="font-mono text-sm">{selected.n_solic}</b><h2 className="text-lg font-bold">Acompanhamento da solicitação</h2></div><button aria-label="Fechar" className="thermo-icon-button" onClick={() => setSelected(null)}><X className="size-4" /></button></header><div className="space-y-2">{items.map((item) => <article className="rounded-md border p-3" key={`${item.solic_id}-${item.carr_id}`}><div className="flex flex-wrap justify-between gap-2"><span><b>{item.codigo_produto}</b> · {item.descricao}</span><span className="font-semibold">{Number(item.quantidade_solicitada ?? item.quantidade).toLocaleString('pt-BR')} {item.unidade}</span></div><p className="mt-2 text-xs text-slate-600">Status: {item.status} · Destino: {item.nome_local || item.cod_local || '—'}</p></article>)}</div><p className="mt-4 rounded-md bg-blue-50 p-3 text-sm text-blue-900">Esta visão é somente para acompanhamento. Operações físicas ficam na aba Tela de separação.</p></section></div>}
  </section>
}
