-- Criar tabela public.historico_pedido_originalis
CREATE TABLE IF NOT EXISTS public.historico_pedido_originalis (
    aprovado_por text,
    cliente text,
    control text,
    data_aprovacao text,
    data_da_entrega_futura text,
    data_entrega text,
    data_finalizacao text,
    data_integracao text,
    esq_esf text,
    estado text,
    expedido_por text,
    finalizado_por text,
    glide_row_id text,
    impressao_logistica text,
    impressao_producao text,
    integrado_por text,
    modelo text,
    nota_fiscal text,
    observacao text,
    opcional text,
    ordem_de_producao text,
    pedido text,
    qty text,
    situacao text,
    qty_em_estoque text,
    redespacho text,
    situacao text,
    transportadora text,
    veiculo text,
    volumes text
);
