-- Criar tabela public.historico_op_iapp gerada automaticamente em 2025-10-20T18:24:27
CREATE TABLE IF NOT EXISTS public.historico_op_iapp (
    produto_identificacao text,
    produto_descricao text,
    projeto numeric,
    ficha_tecnica_identificacao bigint,
    ficha_tecnica_descricao text,
    ficha_tecnica_mod bigint,
    ficha_tecnica_ggf bigint,
    cliente text,
    status text,
    identificacao bigint,
    data_de_abertura date,
    data_prevista_inicio timestamp,
    data_prevista_final timestamp,
    qtde_a_produzir bigint,
    data_de_criacao timestamp,
    tempo_total numeric,
    data_de_encerramento timestamp,
    data_previsao_de_faturamento timestamp,
    data_de_previsao_de_entrega timestamp,
    lote_antecipado numeric,
    documento numeric,
    vcp numeric,
    data_do_vcp timestamp,
    volumes bigint,
    pedido_xped numeric,
    origem text,
    empenhada numeric,
    mao_de_obra_direta bigint,
    gastos_gerais_de_fabricacao bigint,
    ordem_nivel_anterior numeric,
    linha_de_producao text,
    total_qtde_produzida bigint,
    origem_completa text,
    usuario_criador text
);
