var OMIE_APP_KEY = 'PUT_YOUR_APP_KEY_HERE';
var OMIE_APP_SECRET = 'PUT_YOUR_APP_SECRET_HERE';

var XMLHttpRequest = require("xmlhttprequest").XMLHttpRequest;
var PedidoVendaProdutoJsonClient=function(){
	this._EndPoint="https://app.omie.com.br/api/v1/produtos/pedido/";
	this._Call=function(method,param,cb){
		var server= new XMLHttpRequest();
		server.open("POST",this._EndPoint,cb!=null);
		server.setRequestHeader("Content-Type","application/json");
		var req=JSON.stringify({call:method,app_key:OMIE_APP_KEY,app_secret:OMIE_APP_SECRET,param:(param)?param:[]});
		if(cb){
			server.onreadystatechange=this._EndCall;
			server.cb=cb;
			server.send(req);
			return server;
		}else{
			server.send(req);
			var res=JSON.parse(server.responseText);
			delete(server);
			return res;
		}
	};
	this._EndCall=function(e){
		var server=this;
		if(server.readyState!=4)
			return;
		if(server.status!=200)
			throw(new Exception("AJAX error "+server.status+": "+server.statusText));
		server.cb(JSON.parse(server.responseText));
		server.cb=null;
		delete(server);
	};
	this.IncluirPedido=function(
		pedido_venda_produto,
		_cb
	){
		return this._Call(
			"IncluirPedido",
			[
			pedido_venda_produto
			],
			(_cb)?_cb:null
		);
	};
	this.AlterarPedidoVenda=function(
		pedido_venda_produto,
		_cb
	){
		return this._Call(
			"AlterarPedidoVenda",
			[
			pedido_venda_produto
			],
			(_cb)?_cb:null
		);
	};
	this.ConsultarPedido=function(
		pvpConsultarRequest,
		_cb
	){
		return this._Call(
			"ConsultarPedido",
			[
			pvpConsultarRequest
			],
			(_cb)?_cb:null
		);
	};
	this.ListarPedidos=function(
		pvpListarRequest,
		_cb
	){
		return this._Call(
			"ListarPedidos",
			[
			pvpListarRequest
			],
			(_cb)?_cb:null
		);
	};
	this.ExcluirPedido=function(
		pvpExcluirRequest,
		_cb
	){
		return this._Call(
			"ExcluirPedido",
			[
			pvpExcluirRequest
			],
			(_cb)?_cb:null
		);
	};
	this.StatusPedido=function(
		pvpStatusRequest,
		_cb
	){
		return this._Call(
			"StatusPedido",
			[
			pvpStatusRequest
			],
			(_cb)?_cb:null
		);
	};
	this.TrocarEtapaPedido=function(
		pvpTrocarEtapaRequest,
		_cb
	){
		return this._Call(
			"TrocarEtapaPedido",
			[
			pvpTrocarEtapaRequest
			],
			(_cb)?_cb:null
		);
	};
	this.AlterarPedFaturado=function(
		pvpAlterarPedFatRequest,
		_cb
	){
		return this._Call(
			"AlterarPedFaturado",
			[
			pvpAlterarPedFatRequest
			],
			(_cb)?_cb:null
		);
	};
	this.SimularImpostos=function(
		pvpSimularImpRequest,
		_cb
	){
		return this._Call(
			"SimularImpostos",
			[
			pvpSimularImpRequest
			],
			(_cb)?_cb:null
		);
	};
	this.DevolverPedido=function(
		pvpDevolverRequest,
		_cb
	){
		return this._Call(
			"DevolverPedido",
			[
			pvpDevolverRequest
			],
			(_cb)?_cb:null
		);
	};
	this.agropecuario=function(){
		this.cNumReceita=null;
		this.cCpfResponsavel=null;
		this.nTipoGuia=null;
		this.cUFGuia=null;
		this.cSerieGuia=null;
		this.nNumGuia=null;
	};
	this.cabecalho=function(){
		this.codigo_pedido=null;
		this.codigo_pedido_integracao=null;
		this.numero_pedido=null;
		this.sequencial=null;
		this.codigo_cliente=null;
		this.codigo_cliente_integracao=null;
		this.data_previsao=null;
		this.quantidade_itens=null;
		this.etapa=null;
		this.codigo_parcela=null;
		this.qtde_parcelas=null;
		this.origem_pedido=null;
		this.codigo_cenario_impostos=null;
		this.bloqueado=null;
		this.importado_api=null;
		this.codigo_empresa=null;
		this.codigo_empresa_integracao=null;
		this.tipo_desconto_pedido=null;
		this.perc_desconto_pedido=null;
		this.valor_desconto_pedido=null;
		this.encerrado=null;
		this.enc_motivo=null;
		this.enc_data=null;
		this.enc_hora=null;
		this.enc_user=null;
		this.nao_gerar_boleto=null;
	};
	this.cliente_simul=function(){
		this.clientes_contribuinte=null;
		this.clientes_estado=null;
		this.cidades_codmunibge=null;
		this.clientes_suframa=null;
		this.clientes_cnae=null;
		this.tipo_atividade=null;
		this.optante_simples_nacional=null;
	};
	this.cofins_padrao=function(){
		this.cod_sit_trib_cofins=null;
		this.tipo_calculo_cofins=null;
		this.base_cofins=null;
		this.aliq_cofins=null;
		this.qtde_unid_trib_cofins=null;
		this.valor_unid_trib_cofins=null;
		this.valor_cofins=null;
	};
	this.cofins_st=function(){
		this.cod_sit_trib_cofins_st=null;
		this.tipo_calculo_cofins_st=null;
		this.base_cofins_st=null;
		this.aliq_cofins_st=null;
		this.qtde_unid_trib_cofins_st=null;
		this.valor_unid_trib_cofins_st=null;
		this.margem_cofins_st=null;
		this.valor_cofins_st=null;
	};
	this.combustivel=function(){
		this.cCodigoANP=null;
		this.cDescrANP=null;
		this.cCODIF=null;
		this.nPercGLP=null;
		this.nPercGasNacional=null;
		this.nPercGasImportado=null;
		this.nValorPartida=null;
		this.nQtdeFatTempAmb=null;
		this.cUFConsumoComb=null;
		this.nBC_CIDE=null;
		this.nAliquota_CIDE=null;
		this.nValor_CIDE=null;
		this.nBC_UFRem=null;
		this.nValorUFRem=null;
		this.nBC_UFDest=null;
		this.nValorUFDest=null;
	};
	this.csll=function(){
		this.aliq_csll=null;
		this.valor_csll=null;
	};
	this.departamentos=function(){
		this.cCodDepto=null;
		this.nPerc=null;
		this.nValor=null;
		this.nValorFixo=null;
	};
	this.det=function(){
		this.ide=null;
		this.produto=null;
		this.observacao=null;
		this.inf_adic=null;
		this.imposto=null;
		this.rastreabilidade=null;
		this.combustivel=null;
		this.tributavel=null;
		this.lote_validade=null;
	};
	this.ide=function(){
		this.codigo_item_integracao=null;
		this.codigo_item=null;
		this.simples_nacional=null;
		this.acao_item=null;
		this.id_ordem_producao=null;
		this.regra_impostos=null;
	};
	this.produto=function(){
		this.codigo_produto=null;
		this.codigo_produto_integracao=null;
		this.codigo=null;
		this.descricao=null;
		this.cfop=null;
		this.ncm=null;
		this.ean=null;
		this.unidade=null;
		this.quantidade=null;
		this.valor_unitario=null;
		this.codigo_tabela_preco=null;
		this.valor_mercadoria=null;
		this.tipo_desconto=null;
		this.percentual_desconto=null;
		this.valor_desconto=null;
		this.valor_deducao=null;
		this.valor_icms_desonerado=null;
		this.motivo_icms_desonerado=null;
		this.valor_total=null;
		this.indicador_escala=null;
		this.cnpj_fabricante=null;
		this.kit=null;
		this.componente_kit=null;
		this.codigo_item_kit=null;
		this.reservado=null;
	};
	this.observacao=function(){
		this.obs_item=null;
	};
	this.inf_adic=function(){
		this.peso_liquido=null;
		this.peso_bruto=null;
		this.numero_pedido_compra=null;
		this.item_pedido_compra=null;
		this.dados_adicionais_item=null;
		this.nao_movimentar_estoque=null;
		this.nao_gerar_financeiro=null;
		this.codigo_categoria_item=null;
		this.codigo_beneficio_fiscal=null;
		this.numero_fci=null;
		this.codigo_local_estoque=null;
		this.codigo_cenario_impostos_item=null;
		this.nao_somar_total=null;
	};
	this.imposto=function(){
		this.icms_sn=null;
		this.icms=null;
		this.icms_st=null;
		this.icms_ie=null;
		this.icms_efet=null;
		this.ipi=null;
		this.pis_padrao=null;
		this.pis_st=null;
		this.cofins_padrao=null;
		this.cofins_st=null;
		this.inss=null;
		this.csll=null;
		this.irrf=null;
		this.iss=null;
	};
	this.rastreabilidade=function(){
		this.numeroLote=null;
		this.qtdeProdutoLote=null;
		this.dataFabricacaoLote=null;
		this.dataValidadeLote=null;
		this.codigoAgregacaoLote=null;
	};
	this.tributavel=function(){
		this.cUnidTrib=null;
		this.nQuantTrib=null;
		this.nValorTrib=null;
		this.cEanTrib=null;
	};
	this.lote_validade=function(){
		this.nIdLote=null;
		this.nQtdLote=null;
	};
	this.det_simul=function(){
		this.codigo_cenario_impostos_item=null;
		this.produto_simul=null;
	};
	this.produto_simul=function(){
		this.codigo_produto=null;
		this.codigo_produto_integracao=null;
		this.codigo_item_integracao=null;
		this.quantidade=null;
		this.valor_unitario=null;
		this.valor_desconto=null;
	};
	this.det_simul_resp=function(){
		this.codigo_cenario_impostos_item=null;
		this.produto_simul_resp=null;
		this.imposto=null;
	};
	this.produto_simul_resp=function(){
		this.codigo_produto=null;
		this.codigo_produto_integracao=null;
		this.codigo_item_integracao=null;
		this.codigo_item_kit=null;
		this.quantidade=null;
		this.valor_unitario=null;
		this.valor_desconto=null;
		this.valor_icms_desonerado=null;
		this.motivo_icms_desonerado=null;
		this.valor_total=null;
		this.cfop=null;
	};
	this.exportacao=function(){
		this.nao_exportacao=null;
		this.local_embarque=null;
		this.uf_embarque=null;
		this.local_despacho=null;
	};
	this.frete=function(){
		this.codigo_transportadora=null;
		this.codigo_transportadora_integracao=null;
		this.modalidade=null;
		this.placa=null;
		this.placa_estado=null;
		this.registro_transportador=null;
		this.quantidade_volumes=null;
		this.especie_volumes=null;
		this.marca_volumes=null;
		this.numeracao_volumes=null;
		this.peso_liquido=null;
		this.peso_bruto=null;
		this.valor_frete=null;
		this.valor_seguro=null;
		this.numero_lacre=null;
		this.outras_despesas=null;
		this.veiculo_proprio=null;
		this.previsao_entrega=null;
		this.codigo_rastreio=null;
		this.icms_retido=null;
		this.codigo_tipo_entrega=null;
		this.link_rastreio=null;
	};
	this.icms_retido=function(){
		this.vServicoTr=null;
		this.vBCRetencaoTr=null;
		this.vAliquotaRetencaoTr=null;
		this.vIcmsRetidoTr=null;
		this.cCfopTr=null;
		this.cCidadeTr=null;
	};
	this.frete_simul=function(){
		this.valor_frete=null;
		this.valor_seguro=null;
		this.outras_despesas=null;
	};
	this.icms=function(){
		this.cod_sit_trib_icms=null;
		this.origem_icms=null;
		this.modalidade_icms=null;
		this.perc_red_base_icms=null;
		this.base_icms=null;
		this.aliq_icms=null;
		this.valor_icms=null;
		this.perc_fcp_icms=null;
		this.base_fcp_icms=null;
		this.valor_fcp_icms=null;
	};
	this.icms_efet=function(){
		this.cod_sit_trib_icms_efet=null;
		this.origem_icms_efet=null;
		this.modalidade_icms_efet=null;
		this.perc_red_base_icms_efet=null;
		this.base_icms_efet=null;
		this.aliq_icms_efet=null;
		this.valor_icms_efet=null;
	};
	this.icms_ie=function(){
		this.base_icms_uf_destino=null;
		this.aliq_icms_FCP=null;
		this.aliq_interna_uf_destino=null;
		this.aliq_interestadual=null;
		this.aliq_partilha_icms=null;
		this.valor_fcp_icms_inter=null;
		this.valor_icms_uf_dest=null;
		this.valor_icms_uf_remet=null;
	};
	this.icms_sn=function(){
		this.cod_sit_trib_icms_sn=null;
		this.origem_icms_sn=null;
		this.aliq_icms_sn=null;
		this.valor_credito_icms_sn=null;
		this.base_icms_sn=null;
		this.valor_icms_sn=null;
	};
	this.icms_st=function(){
		this.cod_sit_trib_icms_st=null;
		this.modalidade_icms_st=null;
		this.perc_red_base_icms_st=null;
		this.base_icms_st=null;
		this.aliq_icms_st=null;
		this.margem_icms_st=null;
		this.valor_icms_st=null;
		this.aliq_icms_opprop=null;
		this.perc_red_base_icms_op=null;
		this.cest=null;
		this.perc_fcp_icms_st=null;
		this.base_fcp_icms_st=null;
		this.valor_fcp_icms_st=null;
	};
	this.ipi=function(){
		this.cod_sit_trib_ipi=null;
		this.tipo_calculo_ipi=null;
		this.enquadramento_ipi=null;
		this.base_ipi=null;
		this.aliq_ipi=null;
		this.qtde_unid_trib_ipi=null;
		this.valor_unid_trib_ipi=null;
		this.valor_ipi=null;
	};
	this.pis_padrao=function(){
		this.cod_sit_trib_pis=null;
		this.tipo_calculo_pis=null;
		this.base_pis=null;
		this.aliq_pis=null;
		this.qtde_unid_trib_pis=null;
		this.valor_unid_trib_pis=null;
		this.valor_pis=null;
	};
	this.pis_st=function(){
		this.cod_sit_trib_pis_st=null;
		this.tipo_calculo_pis_st=null;
		this.base_pis_st=null;
		this.aliq_pis_st=null;
		this.qtde_unid_trib_pis_st=null;
		this.valor_unid_trib_pis_st=null;
		this.margem_pis_st=null;
		this.valor_pis_st=null;
	};
	this.inss=function(){
		this.aliq_inss=null;
		this.valor_inss=null;
	};
	this.irrf=function(){
		this.aliq_irrf=null;
		this.valor_irrf=null;
	};
	this.iss=function(){
		this.base_iss=null;
		this.aliq_iss=null;
		this.valor_iss=null;
		this.retem_iss=null;
	};
	this.infoCadastro=function(){
		this.dInc=null;
		this.hInc=null;
		this.uInc=null;
		this.dAlt=null;
		this.hAlt=null;
		this.uAlt=null;
		this.dCan=null;
		this.hCan=null;
		this.uCan=null;
		this.cancelado=null;
		this.dFat=null;
		this.hFat=null;
		this.uFat=null;
		this.faturado=null;
		this.denegado=null;
		this.autorizado=null;
		this.devolvido=null;
		this.devolvido_parcial=null;
		this.cImpAPI=null;
	};
	this.informacoes_adicionais=function(){
		this.codigo_categoria=null;
		this.codigo_conta_corrente=null;
		this.numero_pedido_cliente=null;
		this.numero_contrato=null;
		this.contato=null;
		this.dados_adicionais_nf=null;
		this.consumidor_final=null;
		this.utilizar_emails=null;
		this.enviar_email=null;
		this.enviar_pix=null;
		this.codVend=null;
		this.codProj=null;
		this.outros_detalhes=null;
		this.impostos_embutidos=null;
		this.meio_pagamento=null;
		this.descr_meio_pagamento=null;
		this.tipo_documento=null;
		this.nfRelacionada=null;
		this.nsu=null;
	};
	this.outros_detalhes=function(){
		this.cNatOperacaoOd=null;
		this.cIndicadorOd=null;
		this.cIndicadorIntOd=null;
		this.cCnpjIntOd=null;
		this.cIdentificadorIntOd=null;
		this.dDataSaidaOd=null;
		this.cHoraSaidaOd=null;
		this.cCnpjCpfOd=null;
		this.cNomeOd=null;
		this.cInscrEstadualOd=null;
		this.cEnderecoOd=null;
		this.cNumeroOd=null;
		this.cComplementoOd=null;
		this.cBairroOd=null;
		this.cEstadoOd=null;
		this.cCidadeOd=null;
		this.cCEPOd=null;
		this.cSepararEnderecoOd=null;
		this.cTelefoneOd=null;
		this.cCnpjCpfOdRet=null;
		this.cNomeOdRet=null;
		this.cInscrEstadualOdRet=null;
		this.cEnderecoOdRet=null;
		this.cNumeroOdRet=null;
		this.cComplementoOdRet=null;
		this.cBairroOdRet=null;
		this.cEstadoOdRet=null;
		this.cCidadeOdRet=null;
		this.cCEPOdRet=null;
		this.cSepararEnderecoOdRet=null;
		this.cTelefoneOdRet=null;
	};
	this.nfRelacionada=function(){
		this.cChaveRef=null;
		this.nNFRef=null;
		this.cSerieRef=null;
		this.dtEmissaoRef=null;
		this.cnpjEmitRef=null;
		this.cUfRef=null;
		this.nNfPR=null;
		this.cSeriePR=null;
		this.dtEmissaoPR=null;
		this.cnpjPR=null;
		this.InscrEstPR=null;
		this.cUfPR=null;
		this.nCOORef=null;
		this.nECFRef=null;
		this.indPresenca=null;
		this.indIntermediario=null;
		this.cnpjIntermediario=null;
		this.identIntermediario=null;
		this.nrProdutorRural=null;
		this.nrNF=null;
		this.nrCupomFiscal=null;
		this.nrModelo1_1A=null;
		this.cSigNFRef=null;
	};
	this.itens=function(){
		this.codigo_produto=null;
		this.quantidade=null;
	};
	this.lancamentos=function(){
		this.nSequencia=null;
		this.cNaturezaDocumento=null;
		this.nValorDocumento=null;
		this.dDataDocumento=null;
		this.cTipoDocumento=null;
		this.cCategoria=null;
		this.nContaCorrente=null;
		this.cOrigem=null;
		this.cObs=null;
		this.nProjeto=null;
		this.nVendedor=null;
	};
	this.lista_parcelas=function(){
		this.parcela=null;
	};
	this.parcela=function(){
		this.numero_parcela=null;
		this.valor=null;
		this.percentual=null;
		this.data_vencimento=null;
		this.quantidade_dias=null;
		this.tipo_documento=null;
		this.meio_pagamento=null;
		this.descr_meio_pagamento=null;
		this.nsu=null;
		this.nao_gerar_boleto=null;
		this.parcela_adiantamento=null;
		this.categoria_adiantamento=null;
		this.conta_corrente_adiantamento=null;
		this.bandeira=null;
		this.cnpj_fin=null;
	};
	this.ListaNfe=function(){
		this.numero_lote=null;
		this.status_lote=null;
		this.recibo=null;
		this.contingencia=null;
		this.numero_nfe=null;
		this.serie_nfe=null;
		this.status_nfe=null;
		this.chave_nfe=null;
		this.protocolo=null;
		this.tipo=null;
		this.data_emissao=null;
		this.hora_emissao=null;
		this.data_fatura=null;
		this.hora_fatura=null;
		this.data_saida=null;
		this.hora_saida=null;
		this.mensagens=null;
		this.xml_distr=null;
		this.danfe=null;
	};
	this.mensagens=function(){
		this.cCodigo=null;
		this.cDescricao=null;
		this.cCorrecao=null;
	};
	this.market_place=function(){
		this.nTaxa=null;
		this.nEnvio=null;
	};
	this.nrProdutorRural=function(){
		this.cAcaoItem=null;
		this.nrNumero=null;
		this.nrSerie=null;
		this.nrDtEmissao=null;
		this.nrCnpjCpf=null;
		this.nrIE=null;
		this.nrUF=null;
	};
	this.nrNF=function(){
		this.cAcaoItem=null;
		this.nrChave=null;
	};
	this.nrCupomFiscal=function(){
		this.cAcaoItem=null;
		this.nrCOO=null;
		this.nrNumeroECF=null;
	};
	this.nrModelo1_1A=function(){
		this.cAcaoItem=null;
		this.nrNumero=null;
		this.nrSerie=null;
		this.nrDtEmissao=null;
		this.nrCnpjCpf=null;
		this.nrUF=null;
	};
	this.observacoes=function(){
		this.obs_venda=null;
	};
	this.pedido_venda_produto=function(){
		this.cabecalho=null;
		this.departamentos=null;
		this.frete=null;
		this.informacoes_adicionais=null;
		this.lista_parcelas=null;
		this.observacoes=null;
		this.det=null;
		this.market_place=null;
		this.total_pedido=null;
		this.infoCadastro=null;
		this.exportacao=null;
		this.lancamentos=null;
		this.agropecuario=null;
	};
	this.total_pedido=function(){
		this.base_calculo_icms=null;
		this.base_calculo_st=null;
		this.valor_pis=null;
		this.valor_cofins=null;
		this.valor_csll=null;
		this.valor_icms=null;
		this.valor_st=null;
		this.valor_inss=null;
		this.valor_IPI=null;
		this.valor_ir=null;
		this.valor_iss=null;
		this.valor_deducoes=null;
		this.valor_descontos=null;
		this.valor_mercadorias=null;
		this.valor_total_pedido=null;
	};
	this.pedido_venda_produto_response=function(){
		this.codigo_pedido=null;
		this.codigo_pedido_integracao=null;
		this.codigo_status=null;
		this.descricao_status=null;
		this.numero_pedido=null;
	};
	this.pvpAlterarPedFatRequest=function(){
		this.codigo_pedido=null;
		this.codigo_pedido_integracao=null;
		this.numero_pedido=null;
		this.codigo_rastreio=null;
		this.link_rastreio=null;
		this.previsao_entrega=null;
		this.obs_venda=null;
	};
	this.pvpAlterarPedFatResponse=function(){
		this.codigo_pedido=null;
		this.codigo_pedido_integracao=null;
		this.numero_pedido=null;
		this.codigo_status=null;
		this.descricao_status=null;
	};
	this.pvpConsultarRequest=function(){
		this.codigo_pedido=null;
		this.codigo_pedido_integracao=null;
		this.numero_pedido=null;
	};
	this.pvpConsultarResponse=function(){
		this.pedido_venda_produto=null;
	};
	this.pvpDevolverRequest=function(){
		this.codigo_pedido=null;
		this.codigo_pedido_integracao=null;
		this.itens=null;
	};
	this.pvpDevolverResponse=function(){
		this.cCodStatus=null;
		this.cDesStatus=null;
		this.nIdDevolucao=null;
	};
	this.pvpExcluirRequest=function(){
		this.codigo_pedido=null;
		this.codigo_pedido_integracao=null;
	};
	this.pvpExcluirResponse=function(){
		this.codigo_pedido=null;
		this.codigo_pedido_integracao=null;
		this.numero_pedido=null;
		this.codigo_status=null;
		this.descricao_status=null;
	};
	this.pvpListarRequest=function(){
		this.pagina=null;
		this.registros_por_pagina=null;
		this.apenas_importado_api=null;
		this.ordenar_por=null;
		this.filtrar_por_data_de=null;
		this.filtrar_por_data_ate=null;
		this.filtrar_por_hora_de=null;
		this.filtrar_por_hora_ate=null;
		this.filtrar_apenas_inclusao=null;
		this.filtrar_apenas_alteracao=null;
		this.filtrar_por_cliente=null;
		this.filtrar_por_vendedor=null;
		this.filtrar_por_projeto=null;
		this.etapa=null;
		this.numero_pedido_de=null;
		this.numero_pedido_ate=null;
		this.apenas_resumo=null;
		this.data_previsao_de=null;
		this.data_previsao_ate=null;
		this.data_faturamento_de=null;
		this.data_faturamento_ate=null;
		this.data_emissao_de=null;
		this.data_emissao_ate=null;
		this.data_cancelamento_de=null;
		this.data_cancelamento_ate=null;
		this.status_pedido=null;
		this.ordem_descrescente=null;
	};
	this.pvpListarResponse=function(){
		this.pagina=null;
		this.total_de_paginas=null;
		this.registros=null;
		this.total_de_registros=null;
		this.pedido_venda_produto=null;
	};
	this.pvpSimularImpRequest=function(){
		this.codigo_cliente=null;
		this.cliente_simul=null;
		this.codigo_cliente_integracao=null;
		this.consumidor_final=null;
		this.impostos_embutidos=null;
		this.frete_simul=null;
		this.uf_entrega=null;
		this.indPresenca=null;
		this.det_simul=null;
	};
	this.pvpSimularImpResponse=function(){
		this.codigo_cliente=null;
		this.codigo_cliente_integracao=null;
		this.consumidor_final=null;
		this.frete_simul=null;
		this.uf_entrega=null;
		this.indPresenca=null;
		this.det_simul_resp=null;
	};
	this.pvpStatusRequest=function(){
		this.codigo_pedido=null;
		this.codigo_pedido_integracao=null;
	};
	this.pvpStatusResponse=function(){
		this.codigo_pedido=null;
		this.codigo_pedido_integracao=null;
		this.numero_pedido=null;
		this.etapa=null;
		this.cancelada=null;
		this.faturada=null;
		this.ambiente=null;
		this.valor_total_pedido=null;
		this.ListaNfe=null;
	};
	this.pvpTrocarEtapaRequest=function(){
		this.codigo_pedido=null;
		this.codigo_pedido_integracao=null;
		this.numero_pedido=null;
		this.etapa=null;
	};
	this.pvpTrocarEtapaResponse=function(){
		this.codigo_pedido=null;
		this.codigo_pedido_integracao=null;
		this.numero_pedido=null;
		this.codigo_status=null;
		this.descricao_status=null;
	};
	this.omie_fail=function(){
		this.code=null;
		this.description=null;
		this.referer=null;
		this.fatal=null;
	};
};
module.exports = PedidoVendaProdutoJsonClient;