var OMIE_APP_KEY = 'PUT_YOUR_APP_KEY_HERE';
var OMIE_APP_SECRET = 'PUT_YOUR_APP_SECRET_HERE';

var XMLHttpRequest = require("xmlhttprequest").XMLHttpRequest;
var ProdutosCadastroJsonClient=function(){
	this._EndPoint="https://app.omie.com.br/api/v1/geral/produtos/";
	this._Call=function(method,param,cb){
		var server= new XMLHttpRequest();
		server.open("POST",this._EndPoint,cb!=null);
		server.setRequestHeader("Content-Type","application/json");
		var req=JSON.stringify({call:method,app_key:OMIE_APP_KEY,app_secret:OMIE_APP_SECRET,param:(param)?param:[]});
		if(cb){
			server.onreadystatechange=this._EndCall;
			server.cb=cb;
			server.send(req);
			return server;
		}else{
			server.send(req);
			var res=JSON.parse(server.responseText);
			delete(server);
			return res;
		}
	};
	this._EndCall=function(e){
		var server=this;
		if(server.readyState!=4)
			return;
		if(server.status!=200)
			throw(new Exception("AJAX error "+server.status+": "+server.statusText));
		server.cb(JSON.parse(server.responseText));
		server.cb=null;
		delete(server);
	};
	this.IncluirProduto=function(
		produto_servico_cadastro,
		_cb
	){
		return this._Call(
			"IncluirProduto",
			[
			produto_servico_cadastro
			],
			(_cb)?_cb:null
		);
	};
	this.AlterarProduto=function(
		produto_servico_cadastro,
		_cb
	){
		return this._Call(
			"AlterarProduto",
			[
			produto_servico_cadastro
			],
			(_cb)?_cb:null
		);
	};
	this.ExcluirProduto=function(
		produto_servico_cadastro_chave,
		_cb
	){
		return this._Call(
			"ExcluirProduto",
			[
			produto_servico_cadastro_chave
			],
			(_cb)?_cb:null
		);
	};
	this.ConsultarProduto=function(
		produto_servico_cadastro_chave,
		_cb
	){
		return this._Call(
			"ConsultarProduto",
			[
			produto_servico_cadastro_chave
			],
			(_cb)?_cb:null
		);
	};
	this.IncluirProdutosPorLote=function(
		produto_servico_lote_request,
		_cb
	){
		return this._Call(
			"IncluirProdutosPorLote",
			[
			produto_servico_lote_request
			],
			(_cb)?_cb:null
		);
	};
	this.ListarProdutos=function(
		produto_servico_list_request,
		_cb
	){
		return this._Call(
			"ListarProdutos",
			[
			produto_servico_list_request
			],
			(_cb)?_cb:null
		);
	};
	this.ListarProdutosResumido=function(
		produto_servico_list_request,
		_cb
	){
		return this._Call(
			"ListarProdutosResumido",
			[
			produto_servico_list_request
			],
			(_cb)?_cb:null
		);
	};
	this.UpsertProduto=function(
		produto_servico_cadastro,
		_cb
	){
		return this._Call(
			"UpsertProduto",
			[
			produto_servico_cadastro
			],
			(_cb)?_cb:null
		);
	};
	this.UpsertProdutosPorLote=function(
		produto_servico_lote_request,
		_cb
	){
		return this._Call(
			"UpsertProdutosPorLote",
			[
			produto_servico_lote_request
			],
			(_cb)?_cb:null
		);
	};
	this.AssociarCodIntProduto=function(
		produto_servico_cadastro_chave,
		_cb
	){
		return this._Call(
			"AssociarCodIntProduto",
			[
			produto_servico_cadastro_chave
			],
			(_cb)?_cb:null
		);
	};
	this.armamento=function(){
		this.serie_cano=null;
		this.descr_arma=null;
		this.serie_arma=null;
		this.tipo_arma=null;
	};
	this.caracteristicas=function(){
		this.nCodCaract=null;
		this.cCodIntCaract=null;
		this.cNomeCaract=null;
		this.cConteudo=null;
		this.cExibirItemNF=null;
		this.cExibirItemPedido=null;
		this.cExibirOrdemProd=null;
	};
	this.combustivel=function(){
		this.codigo_anp=null;
		this.descr_anp=null;
		this.percent_glp=null;
		this.percent_gas_nac=null;
		this.percent_gas_imp=null;
		this.valor_part=null;
	};
	this.componentes_kit=function(){
		this.codigo_componente=null;
		this.codigo_produto_componente=null;
		this.quantidade_componente=null;
		this.valor_unitario_componente=null;
		this.local_estoque_componente=null;
	};
	this.dadosIbpt=function(){
		this.aliqFederal=null;
		this.aliqEstadual=null;
		this.aliqMunicipal=null;
		this.fonte=null;
		this.chave=null;
		this.versao=null;
		this.valido_de=null;
		this.valido_ate=null;
	};
	this.imagens=function(){
		this.url_imagem=null;
	};
	this.info=function(){
		this.dInc=null;
		this.hInc=null;
		this.uInc=null;
		this.dAlt=null;
		this.hAlt=null;
		this.uAlt=null;
		this.cImpAPI=null;
	};
	this.medicamento=function(){
		this.cod_anvisa=null;
		this.preco_max_cons=null;
	};
	this.produto_servico_cadastro=function(){
		this.codigo_produto=null;
		this.codigo_produto_integracao=null;
		this.codigo=null;
		this.descricao=null;
		this.unidade=null;
		this.ncm=null;
		this.ean=null;
		this.valor_unitario=null;
		this.codigo_familia=null;
		this.tipoItem=null;
		this.produto_variacao=null;
		this.produto_lote=null;
		this.variacao=null;
		this.id_produto_variacao=null;
		this.recomendacoes_fiscais=null;
		this.peso_liq=null;
		this.peso_bruto=null;
		this.altura=null;
		this.largura=null;
		this.profundidade=null;
		this.marca=null;
		this.modelo=null;
		this.dias_garantia=null;
		this.dias_crossdocking=null;
		this.descr_detalhada=null;
		this.obs_internas=null;
		this.imagens=null;
		this.videos=null;
		this.caracteristicas=null;
		this.tabelas_preco=null;
		this.info=null;
		this.exibir_descricao_nfe=null;
		this.exibir_descricao_pedido=null;
		this.medicamento=null;
		this.combustivel=null;
		this.veiculo=null;
		this.armamento=null;
		this.cst_icms=null;
		this.modalidade_icms=null;
		this.csosn_icms=null;
		this.aliquota_icms=null;
		this.red_base_icms=null;
		this.motivo_deson_icms=null;
		this.per_icms_fcp=null;
		this.codigo_beneficio=null;
		this.cst_pis=null;
		this.aliquota_pis=null;
		this.red_base_pis=null;
		this.cst_cofins=null;
		this.aliquota_cofins=null;
		this.red_base_cofins=null;
		this.cfop=null;
		this.dadosIbpt=null;
		this.codInt_familia=null;
		this.descricao_familia=null;
		this.bloqueado=null;
		this.bloquear_exclusao=null;
		this.importado_api=null;
		this.inativo=null;
		this.componentes_kit=null;
		this.lead_time=null;
		this.aliquota_ibpt=null;
		this.cest=null;
		this.quantidade_estoque=null;
		this.estoque_minimo=null;
		this.origem_imposto=null;
	};
	this.recomendacoes_fiscais=function(){
		this.origem_mercadoria=null;
		this.id_preco_tabelado=null;
		this.id_cest=null;
		this.cupom_fiscal=null;
		this.market_place=null;
		this.indicador_escala=null;
		this.cnpj_fabricante=null;
	};
	this.videos=function(){
		this.url_video=null;
	};
	this.tabelas_preco=function(){
		this.nCodTabPreco=null;
		this.cNomeTabPreco=null;
		this.nValorTabPreco=null;
	};
	this.veiculo=function(){
		this.ano_fabr=null;
		this.ano_modelo=null;
		this.chassi=null;
		this.cilin=null;
		this.cmt=null;
		this.cond_veic=null;
		this.cod_cor_veic=null;
		this.cod_cor_den=null;
		this.descr_cor=null;
		this.dist_eixo=null;
		this.especie_veic=null;
		this.lota_max=null;
		this.cod_modelo=null;
		this.motor=null;
		this.peso_bruto_veic=null;
		this.peso_liquido_veic=null;
		this.potencia=null;
		this.serie_veic=null;
		this.tipo_comb=null;
		this.tipo_oper=null;
		this.tipo_pintura=null;
		this.tipo_restricao=null;
		this.tipo_veic=null;
		this.cond_vin=null;
	};
	this.produto_servico_cadastro_chave=function(){
		this.codigo_produto=null;
		this.codigo_produto_integracao=null;
		this.codigo=null;
	};
	this.produto_servico_list_request=function(){
		this.pagina=null;
		this.registros_por_pagina=null;
		this.apenas_importado_api=null;
		this.ordenar_por=null;
		this.ordem_decrescente=null;
		this.filtrar_por_data_de=null;
		this.filtrar_por_hora_de=null;
		this.filtrar_por_data_ate=null;
		this.filtrar_por_hora_ate=null;
		this.filtrar_apenas_inclusao=null;
		this.filtrar_apenas_alteracao=null;
		this.filtrar_apenas_omiepdv=null;
		this.filtrar_apenas_familia=null;
		this.filtrar_apenas_tipo=null;
		this.filtrar_apenas_descricao=null;
		this.filtrar_apenas_marketplace=null;
		this.filtrar_apenas_pdv=null;
		this.exibir_caracteristicas=null;
		this.exibir_tabelas_preco=null;
		this.caracteristicas=null;
		this.produtosPorCodigo=null;
		this.inativo=null;
		this.ncm=null;
		this.ean=null;
		this.ordem_descrescente=null;
		this.exibir_obs=null;
		this.exibir_kit=null;
		this.exibir_info_variacoes=null;
	};
	this.produtosPorCodigo=function(){
		this.codigo_produto=null;
		this.codigo_produto_integracao=null;
		this.codigo=null;
	};
	this.produto_servico_list_response=function(){
		this.pagina=null;
		this.total_de_paginas=null;
		this.registros=null;
		this.total_de_registros=null;
		this.produto_servico_resumido=null;
	};
	this.produto_servico_resumido=function(){
		this.codigo_produto=null;
		this.codigo_produto_integracao=null;
		this.codigo=null;
		this.descricao=null;
		this.valor_unitario=null;
	};
	this.produto_servico_listfull_response=function(){
		this.pagina=null;
		this.total_de_paginas=null;
		this.registros=null;
		this.total_de_registros=null;
		this.produto_servico_cadastro=null;
	};
	this.produto_servico_lote_request=function(){
		this.lote=null;
		this.produto_servico_cadastro=null;
	};
	this.produto_servico_lote_response=function(){
		this.lote=null;
		this.codigo_status=null;
		this.descricao_status=null;
	};
	this.produto_servico_status=function(){
		this.codigo_produto=null;
		this.codigo_produto_integracao=null;
		this.codigo_status=null;
		this.descricao_status=null;
	};
	this.omie_fail=function(){
		this.code=null;
		this.description=null;
		this.referer=null;
		this.fatal=null;
	};
};
module.exports = ProdutosCadastroJsonClient;