import { render,screen,waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { beforeEach,describe,expect,it,vi } from 'vitest'
import { StockAdjustmentScreen } from './StockAdjustmentScreen'

const gateway=vi.hoisted(()=>({loadAdjustments:vi.fn(),loadAdjustmentLocations:vi.fn(),searchAdjustmentProducts:vi.fn(),createAdjustment:vi.fn(),approveAdjustment:vi.fn(),rejectAdjustment:vi.fn()}))
vi.mock('../../services/stockAdjustmentGateway',async original=>({...await original<typeof import('../../services/stockAdjustmentGateway')>(),...gateway}))
const rows=[{id:1,tipo_operacao:'ENT',codigo:'P1',descricao:'Produto 1',qtd:2,local_estoque:'1',local_nome:'Almox',motivo:'INV',obs:'Inventário',solicitante:'ana',status:'Aguardando aprovação'},{id:2,tipo_operacao:'SAI',codigo:'P2',descricao:'Produto 2',qtd:1,local_estoque:'1',status:'Executado',aprovado_por:'jair.r'}]
describe('StockAdjustmentScreen',()=>{beforeEach(()=>{vi.clearAllMocks();gateway.loadAdjustments.mockResolvedValue({ok:true,registros:rows});gateway.loadAdjustmentLocations.mockResolvedValue({ok:true,locais:[]})})
it('mostra estados reais e bloqueia acesso sem permissão',async()=>{const {rerender}=render(<StockAdjustmentScreen currentUser="jair.r" allowed={false}/>);expect(screen.getByText(/bloqueada/)).toBeInTheDocument();expect(gateway.loadAdjustments).not.toHaveBeenCalled();rerender(<StockAdjustmentScreen currentUser="jair.r" allowed/>);expect(await screen.findByText(/#1/)).toBeInTheDocument();expect(screen.getByText(/Pendentes \(1\)/)).toBeInTheDocument()})
it('abre decisão sem executar escrita e exige frase exata',async()=>{const user=userEvent.setup();render(<StockAdjustmentScreen currentUser="jair.r" allowed/>);await user.click(await screen.findByRole('button',{name:/Executar ajuste/}));expect(screen.getByText(/altera o estoque real/)).toBeInTheDocument();expect(screen.getByRole('button',{name:'Confirmar'})).toBeDisabled();expect(gateway.approveAdjustment).not.toHaveBeenCalled()})
it('expõe histórico executado e formulário ENT/SAI',async()=>{const user=userEvent.setup();render(<StockAdjustmentScreen currentUser="jair.r" allowed/>);await user.click(await screen.findByRole('button',{name:/Histórico/}));expect(screen.getByText('Executado')).toBeInTheDocument();await user.click(screen.getByRole('button',{name:/Nova solicitação/}));await waitFor(()=>expect(gateway.loadAdjustmentLocations).toHaveBeenCalled());expect(screen.getByLabelText('Tipo')).toHaveValue('ENT');expect(screen.getByText(/Digite SOLICITAR ENT/)).toBeInTheDocument()})})
