/* oxlint-disable react/set-state-in-effect */
import { useCallback, useEffect, useMemo, useState } from "react";
import { Download, ExternalLink, FileClock, RefreshCw, Search, Trash2, Upload, X } from "lucide-react";
import * as api from "../../services/qualityManualsGateway";
import type { MainManual, MasterDocument, MasterVersion, ProductManual, ProductSearchResult } from "./types";
type Tab = "principais" | "produtos" | "mestra";
const norm = (value: unknown) => String(value ?? "").toLocaleLowerCase("pt-BR").normalize("NFD").replace(/\p{M}/gu, "");
const codeOf = (value: { codigo_produto?: string; codigo?: string }) => String(value.codigo_produto || value.codigo || "");
export function QualityManualsScreen({ allowed = true, canManageProducts = false, canUploadMaster = false }: { allowed?: boolean; canManageProducts?: boolean; canUploadMaster?: boolean }) {
  const [tab, setTab] = useState<Tab>("principais"); const [query, setQuery] = useState("");
  const [main, setMain] = useState<MainManual[]>([]); const [products, setProducts] = useState<ProductManual[]>([]); const [master, setMaster] = useState<MasterDocument[]>([]);
  const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [selected, setSelected] = useState<ProductManual | null>(null); const [document, setDocument] = useState<MasterDocument | null>(null);
  const load = useCallback(async () => { if (!allowed) return; setLoading(true); setError(""); try { const [a,b,c] = await Promise.all([api.loadMainManuals(), api.loadProductManuals(), api.loadMasterDocuments()]); setMain(a.itens || []); setProducts(b.manuais || []); setMaster(c.itens || []); } catch (e) { setError(e instanceof Error ? e.message : "Falha ao carregar manuais."); } finally { setLoading(false); } }, [allowed]);
  useEffect(() => { void load(); }, [load]);
  const filtered = useMemo(() => { const list = tab === "principais" ? main : tab === "produtos" ? products : master; return list.filter(item => !query || norm(JSON.stringify(item)).includes(norm(query))); }, [tab, query, main, products, master]);
  if (!allowed) return <section role="alert" className="rounded border border-amber-300 bg-amber-50 p-5"><h1 className="font-bold">Acesso não permitido</h1><p>Seu perfil não possui acesso à lista mestra de qualidade.</p></section>;
  return <main className="mx-auto max-w-[1440px] space-y-4 p-3 sm:p-6">
    <header className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-wide text-violet-700">Qualidade</p><h1 className="text-2xl font-bold">Manuais e lista mestra</h1><p className="text-sm text-slate-600">Documentos controlados, manuais de produto e histórico de revisões.</p></div><button onClick={() => void load()} className="min-h-11 rounded bg-slate-800 px-4 font-bold text-white"><RefreshCw className="mr-2 inline size-4"/>Atualizar</button></header>
    <nav aria-label="Categorias" className="grid grid-cols-1 gap-2 sm:grid-cols-3">{([["principais","Manuais principais"],["produtos","Manuais de produtos"],["mestra","Lista mestra"]] as const).map(([key,label]) => <button key={key} aria-current={tab === key ? "page" : undefined} onClick={() => { setTab(key); setQuery(""); }} className={`min-h-11 rounded border px-3 font-bold ${tab === key ? "border-violet-700 bg-violet-700 text-white" : "bg-white"}`}>{label}</button>)}</nav>
    <label className="relative block"><span className="sr-only">Buscar na categoria</span><Search className="absolute left-3 top-3 size-5"/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Buscar título, código, produto ou documento" className="min-h-11 w-full rounded border pl-10 pr-3"/></label>
    {error && <p role="alert" className="rounded border border-red-300 bg-red-50 p-3 text-red-900">{error}</p>}
    {loading && !main.length && !products.length && !master.length ? <p>Carregando documentos…</p> : <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">
      {tab === "principais" && (filtered as MainManual[]).map((item,i) => <article key={item.codigo || item.public_url || i} className="rounded border bg-white p-4"><p className="text-xs font-bold text-violet-700">{item.codigo || "MANUAL"}</p><h2 className="font-bold">{item.titulo || item.nome_exibicao || item.nome_arquivo}</h2><p className="text-sm text-slate-500">{item.nome_arquivo}{item.tamanho_bytes ? ` · ${(item.tamanho_bytes/1048576).toFixed(1)} MB` : ""}</p><a href={item.public_url} target="_blank" rel="noreferrer" className="mt-3 inline-flex min-h-11 items-center gap-2 rounded bg-violet-700 px-4 font-bold text-white">Visualizar <ExternalLink className="size-4"/></a></article>)}
      {tab === "produtos" && (filtered as ProductManual[]).map(item => <article key={item.id} className="rounded border bg-white p-4"><h2 className="font-bold">{item.nome}</h2><p className="text-sm text-slate-500">{item.paginas ?? "—"} páginas · {item.status || "status não informado"}</p><p className="mt-2 text-sm">{item.produtos?.length || 0} produto(s) vinculado(s)</p><div className="mt-3 flex flex-wrap gap-2">{item.url && <a href={item.url} target="_blank" rel="noreferrer" className="inline-flex min-h-11 items-center gap-2 rounded border px-3 font-bold">Visualizar <ExternalLink className="size-4"/></a>}<button onClick={() => setSelected(item)} className="min-h-11 rounded bg-violet-700 px-3 font-bold text-white">Produtos vinculados</button></div></article>)}
      {tab === "mestra" && (filtered as MasterDocument[]).map(item => <article key={item.id} className="rounded border bg-white p-4"><p className="text-xs font-bold text-violet-700">{item.numero_formulario || `Documento ${item.id}`}</p><h2 className="font-bold">{item.descricao || "Sem descrição"}</h2><dl className="mt-2 grid grid-cols-2 gap-2 text-sm"><div><dt className="text-slate-500">Revisão</dt><dd>{item.numero_revisao || "—"}</dd></div><div><dt className="text-slate-500">Classificação</dt><dd>{item.classificacao || "—"}</dd></div><div><dt className="text-slate-500">Autor</dt><dd>{item.autor || "—"}</dd></div><div><dt className="text-slate-500">Próxima revisão</dt><dd>{item.proxima_revisao || "—"}</dd></div></dl><button onClick={() => setDocument(item)} className="mt-3 inline-flex min-h-11 items-center gap-2 rounded bg-violet-700 px-3 font-bold text-white"><FileClock className="size-4"/>Documento e versões</button></article>)}
      {!filtered.length && <p className="col-span-full rounded border bg-slate-50 p-5 text-center text-slate-600">Nenhum item encontrado.</p>}
    </section>}
    {selected && <ProductsDialog manual={selected} canManage={canManageProducts} close={() => setSelected(null)} reload={load}/>} {document && <DocumentDialog item={document} canUpload={canUploadMaster} close={() => setDocument(null)} reload={load}/>} 
  </main>;
}
function Modal({ title, close, children }: { title: string; close: () => void; children: React.ReactNode }) { return <div role="dialog" aria-modal="true" aria-label={title} className="fixed inset-0 z-50 flex items-end bg-black/50 sm:items-center sm:justify-center" onMouseDown={e => e.target === e.currentTarget && close()}><section className="max-h-[92vh] w-full overflow-auto rounded-t-xl bg-white p-4 sm:max-w-2xl sm:rounded-xl"><header className="mb-4 flex items-center justify-between"><h2 className="text-xl font-bold">{title}</h2><button aria-label="Fechar" onClick={close} className="min-h-11 min-w-11 rounded border"><X className="mx-auto"/></button></header>{children}</section></div>; }
function ProductsDialog({ manual, canManage, close, reload }: { manual: ProductManual; canManage: boolean; close: () => void; reload: () => Promise<void> }) {
  const [search,setSearch]=useState(""); const [results,setResults]=useState<ProductSearchResult[]>([]); const [target,setTarget]=useState(""); const [action,setAction]=useState<"link"|"unlink">("link"); const [phrase,setPhrase]=useState(""); const [error,setError]=useState("");
  const find=async()=>{try{const data=await api.searchManualProducts(search);setResults(data.produtos||data.items||[])}catch(e){setError(e instanceof Error?e.message:"Falha na busca.")}};
  const execute=async()=>{try{if(action==="link")await api.linkProduct(manual.id,target,phrase);else await api.unlinkProduct(manual.id,target,phrase);await reload();close()}catch(e){setError(e instanceof Error?e.message:"Falha na operação.")}};
  return <Modal title={manual.nome} close={close}><div className="space-y-3">{(manual.produtos||[]).map(p=><div key={codeOf(p)} className="flex items-center justify-between gap-2 rounded border p-3"><span><b>{codeOf(p)}</b><br/><small>{p.descricao}</small></span>{canManage&&<button onClick={()=>{setTarget(codeOf(p));setAction("unlink");setPhrase("")}} className="min-h-11 rounded border border-red-300 px-3 text-red-800"><Trash2 className="mr-1 inline size-4"/>Remover</button>}</div>)}{!(manual.produtos||[]).length&&<p>Nenhum produto vinculado.</p>}{canManage?<><div className="flex gap-2"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Código ou descrição" className="min-h-11 min-w-0 flex-1 rounded border px-3"/><button onClick={()=>void find()} className="rounded bg-slate-800 px-4 text-white">Buscar</button></div>{results.map(p=><button key={p.codigo_produto} onClick={()=>{setTarget(p.codigo_produto);setAction("link");setPhrase("")}} className="block min-h-11 w-full rounded border p-2 text-left"><b>{p.codigo_produto}</b> {p.descricao}</button>)}{target&&<div className="rounded border border-amber-300 bg-amber-50 p-3"><p className="text-sm">Confirme digitando <b>{action==="link"?`VINCULAR PRODUTO ${target} AO MANUAL ${manual.id}`:`REMOVER PRODUTO ${target} DO MANUAL ${manual.id}`}</b></p><input aria-label="Confirmação" value={phrase} onChange={e=>setPhrase(e.target.value)} className="mt-2 min-h-11 w-full rounded border px-3"/><button onClick={()=>void execute()} className="mt-2 min-h-11 rounded bg-amber-700 px-4 font-bold text-white">Confirmar operação</button></div>}</>:<p className="rounded bg-slate-100 p-3 text-sm">Seu perfil pode consultar vínculos, mas não alterá-los.</p>}{error&&<p role="alert" className="text-red-800">{error}</p>}</div></Modal>;
}
function DocumentDialog({ item, canUpload, close, reload }: { item: MasterDocument; canUpload: boolean; close: () => void; reload: () => Promise<void> }) {
  const [versions,setVersions]=useState<MasterVersion[]>([]); const [current,setCurrent]=useState(item); const [file,setFile]=useState<File|null>(null); const [description,setDescription]=useState(""); const [phrase,setPhrase]=useState(""); const [error,setError]=useState("");
  useEffect(()=>{api.loadMasterDocumentFile(item.id).then(x=>{setCurrent(x.item);setVersions(x.historico||[])}).catch(e=>setError(e instanceof Error?e.message:"Falha ao carregar versões."))},[item.id]);
  const upload=async()=>{if(!file)return setError("Selecione um arquivo.");try{await api.uploadMasterRevision(item.id,file,description,phrase);await reload();close()}catch(e){setError(e instanceof Error?e.message:"Falha no envio.")}};
  return <Modal title={`${current.numero_formulario||"Documento"} — Rev. ${current.numero_revisao||"—"}`} close={close}><div className="space-y-3">{current.documento?<div className="flex flex-wrap gap-2"><a href={api.masterFileUrl(item.id,true)} target="_blank" rel="noreferrer" className="inline-flex min-h-11 items-center gap-2 rounded bg-violet-700 px-3 font-bold text-white"><ExternalLink className="size-4"/>Visualizar</a><a href={api.masterFileUrl(item.id)} className="inline-flex min-h-11 items-center gap-2 rounded border px-3 font-bold"><Download className="size-4"/>Baixar</a></div>:<p>Nenhum arquivo enviado.</p>}<h3 className="font-bold">Histórico de versões</h3>{versions.map(v=><div key={v.id} className="flex items-center justify-between gap-2 rounded border p-3"><span><b>Rev. {v.numero_revisao||"—"}</b><br/><small>{v.descricao_alteracao||"Sem descrição"} · {v.inserido_por||"—"}</small></span>{v.documento&&<a href={api.masterFileUrl(item.id,false,v.id)} className="min-h-11 rounded border px-3 py-2">Baixar</a>}</div>)}{!versions.length&&<p className="text-sm text-slate-500">Nenhuma versão registrada.</p>}{canUpload?<div className="rounded border border-amber-300 bg-amber-50 p-3"><h3 className="font-bold">Enviar nova revisão</h3><input aria-label="Arquivo" type="file" onChange={e=>setFile(e.target.files?.[0]||null)} className="mt-2 block w-full"/><input value={description} onChange={e=>setDescription(e.target.value)} placeholder="Descrição da alteração" className="mt-2 min-h-11 w-full rounded border px-3"/><p className="mt-2 text-sm">Confirme digitando <b>ENVIAR REVISAO {item.id}</b></p><input aria-label="Confirmação de revisão" value={phrase} onChange={e=>setPhrase(e.target.value)} className="mt-2 min-h-11 w-full rounded border px-3"/><button onClick={()=>void upload()} className="mt-2 inline-flex min-h-11 items-center gap-2 rounded bg-amber-700 px-4 font-bold text-white"><Upload className="size-4"/>Enviar nova revisão</button></div>:<p className="rounded bg-slate-100 p-3 text-sm">Novas revisões são restritas ao setor de Qualidade. A API não oferece exclusão de arquivo ou versão.</p>}{error&&<p role="alert" className="text-red-800">{error}</p>}</div></Modal>;
}
